### ISSUE TITLE
HDMI Audio

### ISSUE THREAD

**Issue by hieplpvip** [tctien342/Asus-Vivobook-S510UA-Hackintosh#1]
To make HDMI audio work:
1. Use native AppleHDA
2. Inject hda-gfx=onboard-1
3. In Clover, enable FixHDA and UseIntelHDMI
4. Delete FakePCIID_Intel_HD_Graphics.kext
5. Try these kext patches: https://github.com/toleda/audio_CloverHDMI/blob/master/config-hdmi_hd6x0-120.plist.zip (10.12.6-KBL-5912000-Port_0x*-DP2HDM). One of them should work.

I got HDMI audio to work on my Asus UX410UQK: https://github.com/hieplpvip/ASUS-ZENBOOK-UX410-DSDT-PATCH

**Comment by txs** [comment]
Great work!
