### ISSUE TITLE
Disabling discrete graphics GPU（make it to save some bettery）

### ISSUE THREAD

**Issue by Jeffernic** [tctien342/Asus-Vivobook-S510UA-Hackintosh#10]
Hello
Will you plan to Disabling discrete graphics GPU.
If it can be batter for bettery.Please do it.

Very thank you and have a nice day

**Comment by riletan** [comment]
BQ414T Model does not have  any discrete GPU. 
i think this thread should help, good luck 
 https://www.insanelymac.com/forum/topic/295584-disabling-nvidia-optimus-card-on-all-laptops/

**Comment by tctien342** [comment]
Added!

**Comment by LeeBinder** [comment]
This repo has found a new home at the current maintainer's GitHub corner:

https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/

If still interested, please download the latest release from over there, **read the _ReadMe_ completely at least once**, and follow all instructions all the way to the end.

In case an issue arises, please post it via the issues section over there.

This issue will now be closed.
