### ISSUE TITLE
Same codec as you but audio not working 

### ISSUE THREAD

**Issue by DJohnston79** [tctien342/Asus-Vivobook-S510UA-Hackintosh#11]
I have the same audio codec I believe in my vivobook S405UA and am running mojave. i have tried lilu, alc . and patched hda with/without irq fix in clover and cannot get audio recognized. Voodoohda works but no hdmi audio. Any suggestions?

**Comment by tctien342** [comment]
to use appleALC your kext in Mac System should not touched, try reinstall your Mac OS then use it again, u can try my config.plis, I think it will work with all vivobook, (use config.plist + all patched SSDT)

**Comment by DJohnston79** [comment]
I got it figured out. i have cx 8150. 

Thanks for your advice
