### ISSUE TITLE
Battery percentage is not updating and always showing zero.

### ISSUE THREAD

**Issue by jonathan48** [tctien342/Asus-Vivobook-S510UA-Hackintosh#12]
Hi,your repository  works pretty well on my Asus 510UF-EJ303T.Everything is working but the problem is that the battery percentage is not updating and it is always showing zero.i tried patching with rehabman's dsdt patch but in vain. tried apple smart battery manager kext but that doesnt work also.i hope you give me a solution. thank you.
![47061442_2392943187417472_2737410784928727040_n](https://user-images.githubusercontent.com/45461062/49230142-324bfa80-f419-11e8-895f-16a3acd7b42e.jpg)

**Comment by DJohnston79** [comment]
Try and use his batter ssdt and put in acpi>patched . It worked for my asus

**Comment by LeeBinder** [comment]
This repo has found a new home at the current maintainer's GitHub corner:

https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/

If still interested, please download the latest release from over there, **read the _ReadMe_ completely at least once**, and follow all instructions all the way to the end.

In case an issue arises, please post it via the issues section over there.

This issue will now be closed.
