### ISSUE TITLE
Bluetooth issue after wake. 

### ISSUE THREAD

**Issue by riletan** [tctien342/Asus-Vivobook-S510UA-Hackintosh#13]
Hi ông,
 Tui có follow theo guide của ông để cài cho con s510uq của tui (bản có dgpu 940m) 
Hiện máy đang chạy ngon mac 10.14.1  nhưng có 1 số lỗi nhỏ sau: (không biết ông có bị như tui không)
1.  Bluetooth is not available: Cái này bị sau khi sleep mà không có cắm adapter sạc, phải reboot lại. Nếu có cắm thì không sao hết.
Cái dw1560  của tui là bcm20702
2. NVRAM hình như có vấn đề, mỗi lần reboot là các thiết lập cái touchpad + mouse bị reset về mặc định
3. Fn + f9 không có disable touchpad được, đội sáng max của đèn nền bàn phím khá là tối, không bằng lúc bên window
4. Thỉnh thoảng lúc tăng giảm âm lượng 1 nấc thì nó bị mute, phải tăng giảm thêm nữa nó mới có tiếng trở lại. 

I am looking forward to hearing from you :D 
[EFI.zip](https://github.com/tctien342/Asus-Vivobook-S510UA-High-Sierra-10.13-Hackintosh/files/2632767/EFI.zip)

Thanks and best regards.

**Comment by LeeBinder** [comment]
This repo has found a new home at the current maintainer's GitHub corner:

https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/

If still interested, please download the latest release from over there, **read the _ReadMe_ completely at least once**, and follow all instructions all the way to the end.

In case an issue arises, please post it via the issues section over there.

This issue will now be closed.
