### ISSUE TITLE
Make DSDT patches into source code instead of compiled files.

### ISSUE THREAD

**Issue by Piero512** [tctien342/Asus-Vivobook-S510UA-Hackintosh#15]
I think this is necessary, as to track what patches have been applied and how they modify the system. (Comments get lost when decompiling AML files)

**Comment by LeeBinder** [comment]
This repo has found a new home at the current maintainer's GitHub corner:

https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/

If still interested, please download the latest release from over there, **read the _ReadMe_ completely at least once**, and follow all instructions all the way to the end.

In case an issue arises, please post it via the issues section over there.

This issue will now be closed.
