### ISSUE TITLE
Card wifi dw1560– bàn phím S510UQ

### ISSUE THREAD

**Issue by vanhieptech** [tctien342/Asus-Vivobook-S510UA-Hackintosh#17]
1. Bạn ơi cho mình hỏi thử card wifi bạn mua giá bao nhiêu d ạ...bạn mua ở đâu chỉ chỗ mình với được không.?
2.Bàn phím máy mình có mấy phím kí tự nhận sai tùm lum hết bạn biết cách khắc phục sao không?
Cảm ơn trước nhaa.

**Comment by tctien342** [comment]
#1 mua ở đâu nè: https://sites.google.com/site/wififorhackintosh/
#2 bạn vô cài đặt bàn phím ấy: Setting -> Keyboard -> Change Keyboard Type.. r làm theo nó nhé

**Comment by LeeBinder** [comment]
This repo has found a new home at the current maintainer's GitHub corner:

https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/

If still interested, please download the latest release from over there, **read the _ReadMe_ completely at least once**, and follow all instructions all the way to the end.

In case an issue arises, please post it via the issues section over there.

This issue will now be closed.
