### ISSUE TITLE
SD Reader and Audio HDMI dont work

### ISSUE THREAD

**Issue by solirjin** [tctien342/Asus-Vivobook-S510UA-Hackintosh#19]
- i tried connecting to samsung TV but its audio isnt working, display is okay. I read https://github.com/tctien342/Asus-Vivobook-S510UA-High-Sierra-10.13-Hackintosh/issues/1, so your efi hasnt updated yet, right?
- SD card Reader is not working right?

**Comment by tctien342** [comment]
Test it with newest commit!

**Comment by solirjin** [comment]
Does It work with bios 303?

**Comment by tctien342** [comment]
@solirjin it should work :)), just test it and report

**Comment by solirjin** [comment]
> @solirjin it should work :)), just test it and report

im using it, it's good, but do you know how to activate imess ? I can use only icloud now

**Comment by solirjin** [comment]
> @solirjin it should work :)), just test it and report

hey, fn + backlit keyboard doesnt work, at the first place it set on, but after restart, it's off. I can't turn on it with fn+backlit. I think it's an issue

**Comment by solirjin** [comment]
> @solirjin it should work :)), just test it and report

everything works fine, but i have the problem with touchpad, for example, when im in full screen at chrome, and swipe left to come back destop with 3 fingers touch, but it results in comming back the previous page on chrome ( it realises just 2 fingers). It sometimes happens, not always

**Comment by LeeBinder** [comment]
This repo has found a new home at the current maintainer's GitHub corner:

https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/

If still interested, please download the latest release from over there, **read the _ReadMe_ completely at least once**, and follow all instructions all the way to the end.

In case an issue arises, please post it via the issues section over there.

This issue will now be closed.
