### ISSUE TITLE
How do I properly upgrade to the latest commit? 

### ISSUE THREAD

**Issue by HunterAhlquist** [tctien342/Asus-Vivobook-S510UA-Hackintosh#20]
Every time I try to upgrade to the latest kexts, dstd patches, etc. I break my install and I have to restore from backup. Can you make a step-by-step of how you upgrade from the previous commit.
(sorry for making this an issue, i dont know how to direct message on github)

**Comment by LeeBinder** [comment]
This repo has found a new home at the current maintainer's GitHub corner:

https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/

If still interested, please download the latest release from over there, **read the _ReadMe_ completely at least once**, and follow all instructions all the way to the end.

In case an issue arises, please post it via the issues section over there.

This issue will now be closed.
