### ISSUE TITLE
Black Screen 

### ISSUE THREAD

**Issue by drunkenmyno** [tctien342/Asus-Vivobook-S510UA-Hackintosh#22]
Hello guys :)

i have an Asus Vivobook X705UA with the same hardware specification

but the graphic dont work i see in your config.plist no Intel Injector ID for the Intel UHD 620 

if i use your config.plist the screen stays black on boot 

Did i something wrong ?

**Comment by LeeBinder** [comment]
This repo has found a new home at the current maintainer's GitHub corner:

https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/

If still interested, please download the latest release from over there, **read the _ReadMe_ completely at least once**, and follow all instructions all the way to the end.

In case an issue arises, please post it via the issues section over there.

This issue will now be closed.
