### ISSUE TITLE
S530UA Touchpad không hoạt động

### ISSUE THREAD

**Issue by superzeldalink** [tctien342/Asus-Vivobook-S510UA-Hackintosh#23]
S530UA có touchpad elan1300 như S510UA nhưng em cài kext và ssdt-elan vào clover thì System Preferences hiện nhưng không dùng được.
Ad có thể giúp em được k ạ ?
E cảm ơn.

**Comment by awebhay** [comment]
Mình cũng bị giống bạn. Nếu remove hết ketch Voodool2C chỉ để lại VoodooI2CElan.ketch thôi thì mới xài được nhưng rất giật.

**Comment by superzeldalink** [comment]
Mình fix bằng cách tắt 2 cái DSDT patch GPI0 to XSTA với ETPD to XCRS ở Clover là đc
