### ISSUE TITLE
10.14.4 update issues

### ISSUE THREAD

**Issue by colehellman** [tctien342/Asus-Vivobook-S510UA-Hackintosh#27]
After updating to 10.14.4 my boot drive disappeared. I can still boot my laptop, but it is to my Preboot drive. Also, when coming back from sleep my bluetooth is usually disabled. I cannot re-enable it from System Preferences. Other times, my wifi will be disabled as well. Next time, I will definitely wait to update until it has been confirmed to work here.

**Comment by HunterAhlquist** [comment]
I think I can help with the wifi/bluetooth problem.
The issue sources from what I can gather is that the wireless kexts sometimes don't "hook" back into the system in time and it unloads the extension.
My solution was to acquire an alternate build of the BrcmPatchRAM which has an extended delay: https://www.tonymacx86.com/threads/solved-bcm94352z-bluetooth-not-working-after-wake.255014/page-2#post-1799915

After replacing that no more problems! Hope this helps.

**Comment by colehellman** [comment]
@HunterAhlquist Thanks! I will give it a try and report back.
