### ISSUE TITLE
Better build

### ISSUE THREAD

**Issue by hieplpvip** [tctien342/Asus-Vivobook-S510UA-Hackintosh#3]
I've created a universal build for Asus Zenbook [here](https://github.com/hieplpvip/ASUS-ZENBOOK-HACKINTOSH). It's much better organized than your build. I can add support for your laptop if you want.

If you don't want to merge your build into mine, these are several things that will help you:
1. Use [ApfsDriverLoader](https://github.com/acidanthera/ApfsSupportPkg) instead of apfs.efi. It will automatically load apfs.efi from system volume and disable verbose logging too.
2. Don't use OsxAptioFix3Drv-64.efi. Use [AptioMemoryFix](https://github.com/acidanthera/AptioFixPkg). You will have native nvram working.
3. Don't use VoodooHDA, it's kind of a general kext. Use [AppleALC](https://github.com/acidanthera/AppleALC). It will patch AppleHDA for you.
4. IntelGraphicsDVMTFixup.kext is not need if you change DVMT to 64mb in BIOS. Also, IntelGraphicsFixup has been merged into [WhateverGreen](https://github.com/acidanthera/WhateverGreen). You may want to try it.
5. If you have Wifi card working, you can remove NullEthernet. It's only needed when using USB Wifi.
6. It's better to install all kexts to /Library/Extensions. Some kexts won't work from Clover, for example: AppleBacklightInjector (used to get full range brightness), FakeSMC plugins...
7. To get full range brightness from Clover, you can try my [kext](https://github.com/hieplpvip/AppleBacklightFixup)
8. You may want to try hot patching, that way you won't have to patch DSDT every time you update BIOS

**Comment by tctien342** [comment]
Thanks ông nhiều nghen <3!
1. Đã thay
2. Đã thay
3. CX8050 của mình sài appleALC hay patched AppleHDA đều bị hư mic do layout nó chỉ hỗ trợ là 3 nên mình sài VoodooHDA, Bản voodooHDA này mình mod lại đúng node nên âm thanh cũng hay chỉ mỗi tội HDMI audio bug thôi
4. Đã thay
5. Đã thay
6. Chưa thử push vô đó :))), thấy cũng full work, blacklight nhận đủ, nchung ổn hết ông ạ
7. Bug k sài được, bị panic ngay
8. Chưa biết làm hot patch kiểu gì :(

**Comment by hieplpvip** [comment]
Dân việt với nhau mà ko biết :)

**Comment by tctien342** [comment]
@hieplpvip  bác thông cảm =)), đi làm sml nên hay quên!
Trc thấy bác bảo mà em quên rep cmn luôn =)))))))))
Con CX8050 giờ chắc em phải thử tạo cái layout khác cho nó quá :(((

**Comment by hieplpvip** [comment]
Bạn vào [đây](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12) mở issue nhờ patch codec đi

**Comment by hieplpvip** [comment]
mình nghĩ bạn cài lỗi gì đó nên AppleBacklightFixup mới gây panic. Máy mình vẫn xài ok mà

**Comment by tctien342** [comment]
E cũng k biết nữa, cơ mà Backlight máy e ổn, k có vấn đề gì nên em nghĩ k cần kext đó đâu bác

**Comment by hieplpvip** [comment]
[s510ua.zip](https://github.com/tctien342/Asus-Vivobook-S510UA-High-Sierra-10.13-Hackintosh/files/2245903/s510ua.zip)
Bạn dùng thử build này xem sao

**Comment by tctien342** [comment]
Có cách nào build hot patch chỉ gồm i2c, battery, asus FN và instant USB fix k bác :)))

**Comment by hieplpvip** [comment]
Build của mình ngoài mấy cái đó còn vài patch khác nữa bạn. Bạn test thử được thì mình hướng dẫn làm hot patch

**Comment by tctien342** [comment]
Bug bác ới ! bug card đồ họa ! nhận 7 mb thôi

**Comment by hieplpvip** [comment]
Mấy thứ khác sao bạn?

**Comment by hieplpvip** [comment]
Bạn inject id nào cho IGPU?

**Comment by tctien342** [comment]
Mấy thứ khác sơ qua thì ổn bác! chưa thử speedstep, GPU e k cần inject id bở kext nó fix cho r !

**Comment by hieplpvip** [comment]
Bạn có thay file aml trong Clover bằng những file trong thư mục acpi ko?

**Comment by tctien342** [comment]
Thay toàn bộ theo bác luôn, xóa dsdt luôn!

**Comment by hieplpvip** [comment]
bạn gửi thư mục efi mình xem thử

**Comment by tctien342** [comment]
[CLOVER.zip](https://github.com/tctien342/Asus-Vivobook-S510UA-High-Sierra-10.13-Hackintosh/files/2248990/CLOVER.zip)
Đây ạ :3
mic vẫn lỗi như thường nhé, con CX8050 trên con lap em k dùng appleHDA đc

**Comment by hieplpvip** [comment]
Bạn cài thêm FakePCIID_Intel_HD... gpu có hoạt động ko

**Comment by tctien342** [comment]
k bác :))), nát, âm thanh k có luôn, cái SSDT FAN MOD bác sài ngon <3

**Comment by hieplpvip** [comment]
Bạn xóa SSDT-IGPU thử

**Comment by hieplpvip** [comment]
Bạn thử trên 10.14 hay 10.13 vậy?

**Comment by hieplpvip** [comment]
[s510ua.zip](https://github.com/tctien342/Asus-Vivobook-S510UA-High-Sierra-10.13-Hackintosh/files/2250071/s510ua.zip)
Bạn thử bản này xem. Nhớ compile dsl thành aml. Bản này dùng hotpatch đó

**Comment by hieplpvip** [comment]
Bạn dùng Ubuntu dump codec theo hướng dẫn này đi: http://osxarena.com/2015/09/getting-codec-information-for-applehda-patching/

**Comment by tctien342** [comment]
10.14 nhé bác ! e dump codec làm thành layout mới luôn r =))))), vẫn bị ngu mỗi cái micro thôi, thử đủ loại layout

**Comment by hieplpvip** [comment]
Bạn thử build mình mới gửi chưa?

**Comment by tctien342** [comment]
FN bug, pin phải rút sạc cắm lại, bluetooth bug luôn :V và k chịu nhận lại, k biết chuyện gì đã xảy ra!!!
Boot lâu hơn ! trackpad nhận

**Comment by hieplpvip** [comment]
Bạn gửi cho mình output từ tool này đi: https://www.tonymacx86.com/threads/tool-generate-proper-problem-reporting-files.235953/

Máy mình chạy ok cả, boot khoảng 10s thôi

**Comment by tctien342** [comment]
[debug_9634.zip](https://github.com/tctien342/Asus-Vivobook-S510UA-High-Sierra-10.13-Hackintosh/files/2253183/debug_9634.zip)
Đây bác !

**Comment by hieplpvip** [comment]
Bạn cài kext vào /Library/Extensions nhưng chưa fix permission cho kexts nên nó bị lỗi.

[Kext Utility.zip](https://github.com/tctien342/Asus-Vivobook-S510UA-High-Sierra-10.13-Hackintosh/files/2253230/Kext.Utility.zip)
Bạn dùng tool này để fix

**Comment by hieplpvip** [comment]
Nhân tiện bạn gửi mình codec của bạn được không?
Mình chưa patch AppleHDA bao giờ, nên giờ mình muốn thử

**Comment by tctien342** [comment]
Em fix xong trên hot patch của bác r <3, thanks bác nhé, cái SSDT ATK bị bug nên em ngồi mix nó lại 1 chút và ổn r ạ! đợi e dump lại =)) vừa delete sạch

**Comment by tctien342** [comment]
[codec.txt](https://github.com/tctien342/Asus-Vivobook-S510UA-High-Sierra-10.13-Hackintosh/files/2253774/codec.txt)
codec dump!

**Comment by hieplpvip** [comment]
ATK bị bug gì thế?

**Comment by hieplpvip** [comment]
Build của mình dành cho Zenbook mình dùng script để tự động tải, cài đặt kexts, compile dsl.
Nếu bạn muốn mình có thể port script đó cho Vivobook.

Mình mới mở 1 pull request xoá các file .DS_Store đi. Để nó ngứa mắt quá :v

**Comment by hieplpvip** [comment]
Mình thấy patch AppleHDA thì nên nhờ chuyên gia patch.
Bạn dump theo hướng dẫn [này](http://osxarena.com/2016/04/applehda-patch-request/) rồi post lên [đây](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/issues) nhờ patch đi

**Comment by tctien342** [comment]
ATK k sử dụng được thôi bác, tăng giảm sáng bàn phím với ánh sáng màn hình k được nên em kiếm file ssdtt FN sài đcc r ngồi merge code dsdt sang! em merge pull bác vào rồi,sài dot_clean k clean đc =)))! để em thử dump r send qua đó

**Comment by hieplpvip** [comment]
Mình thấy file SSDT-ASUSFN của bạn chỉ khác file SSDT-ATK hai dòng XQ0E() và XQ0F() thôi.
Bạn thử xoá 2 dòng đó xem còn tăng giảm độ sáng được ko?

**Comment by hieplpvip** [comment]
Bạn thử patch AppleHDA nào mà speaker và headphone hoạt động?

**Comment by tctien342** [comment]
em fix r nhé bác, sử dụng custom command trong CodecCommander.kext

**Comment by hieplpvip** [comment]
Bạn patch gì trong CodecCommander vậy?
Góp ý nhỏ là nên dùng SSDT để inject custom command, ko nên patch info.plist

**Comment by tctien342** [comment]
ok e chuyển qua patch bằng ssdt r !
dùng hda-verd thực thi 2 lệnh này bác:
0x19 SET_PIN_WIDGET_CONTROL 0x24
0x1a SET_PIN_WIDGET_CONTROL 0x24

**Comment by DJohnston79** [comment]
Can someone help with my audio? I've got coxenant 8121 apparently and can't get it to work using lilu and ALC 


Laptop is vivobook x405ua
