### ISSUE TITLE
Will you update MacOS catalina?

### ISSUE THREAD

**Issue by oneday95** [tctien342/Asus-Vivobook-S510UA-Hackintosh#30]
Will you update MacOS catalina?

**Comment by LeeBinder** [comment]
Will you specify with required details what's not working for you in macOS Catalina?

**Comment by Nathaneal95S** [comment]
I tried it, it boots up and everything but when you log into the system it lags i don't know if it was because of my slow hdd or because it's a beta...i'll have to backup my ssd and try it on that to confirm. oh and one more problem there is no Audio..and a next problem is that any 32-bit/x86 software will not work its strictly 64-bit/x64...other than that everything worked fine for me...or and i use usb wifi so i cant say if the wifi and bluetooth works for the broadcom card...that card is too expensive to ship to where i'm from...

**Comment by colehellman** [comment]
Catalina drops support for 32-bit apps so it has nothing to do with being a hackintosh

**Comment by LeeBinder** [comment]
One of my bootable macOS backups is on the internal HDD and it's much slower than the one on SSD. Just partition your SSD and boot Catalina from SSD also.

The rest I can't say anything about. I take for granted you are running latest versions of Clover and all kexts --> [kext updater](https://bitbucket.org/profdrluigi/kextupdater/downloads/)

**Comment by DevDivega** [comment]
I have this exact laptop model and Catalina doesn't work for me. I've tried upgrading from Mojave and clean installing the beta and each results in a kernel panic. I've updated all my kexts.

**Comment by LeeBinder** [comment]
I'll wait for 10.15.1, but you all can see if you can find something useful at https://olarila.com/forum/viewtopic.php?f=95&t=10364

**Comment by deniro98** [comment]
Catalina Works!
[YouTube Touchpad](https://www.youtube.com/watch?v=37CCd5ZgeaQ)
[YouTube Finishing install](https://www.youtube.com/watch?v=tPOpDaa_41U)
Touchpad is awesome works! It's like real macbook! 

Not working:
- FN keys  
- brightness display 
- HDMI
- Battery percentage 

UPD. After 6-7 reboots touchpad is not working)))) i don't know how i can fix it)

**Comment by Jeffernic** [comment]
> 卡塔琳娜作品！
> [YouTube觸摸板](https://www.youtube.com/watch?v=37CCd5ZgeaQ)
> [YouTube精加工安裝](https://www.youtube.com/watch?v=tPOpDaa_41U)
> 觸摸板非常棒！就像真正的Macbook！
> 
> 無法運作：
> 
> * FN鍵
> * 亮度顯示
> * HDMI接口
> * 電池百分比
> 
> UPD。6-7重新啟動後，觸摸板無法正常工作））））我不知道該如何解決）

My DW1560 just can connect to wifi.
Could you share how it can work at bluetooth.
i had found a post https://www.insanelymac.com/forum/topic/339175-brcmpatchram2-for-1015-catalina-broadcom-bluetooth-firmware-upload/
But i dont konw how to build it

**Comment by LeeBinder** [comment]
I'm still not on Catalina so can't help. Good luck!

**Comment by LeeBinder** [comment]
This repo has found a new home at the current maintainer's GitHub corner:

https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/

If still interested, please download the latest release from over there, **read the _ReadMe_ completely at least once**, and follow all instructions all the way to the end.

In case an issue arises, please post it via the issues section over there.

This issue will now be closed.
