### ISSUE TITLE
my laptop s510un i7-8550u

### ISSUE THREAD

**Issue by oneday95** [tctien342/Asus-Vivobook-S510UA-Hackintosh#31]
Does this laptop work?

**Comment by adrianorocha-dev** [comment]
Not sure about the exact model, but I'm using another model with an i7-8550u and so far it's working fine.

**Comment by LeeBinder** [comment]
This repo has found a new home at the current maintainer's GitHub corner:

https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/

If still interested, please download the latest release from over there, **read the _ReadMe_ completely at least once**, and follow all instructions all the way to the end.

In case an issue arises, please post it via the issues section over there.

This issue will now be closed.
