### ISSUE TITLE
Cant Start Installation on my S510U

### ISSUE THREAD

**Issue by alfredoarrieta** [tctien342/Asus-Vivobook-S510UA-Hackintosh#32]
Hi, i have an Asus VivoBook S510U, this model does not have a fingerprint reader, but has a 16 Gigs intel optane, it also came with a 1tb phisical sata hard drive which i changed to a Samsung 250 Gigs SSD, im triying to install Mojave with this repository, using the EFI folder in "EFI BQ414T" and the the EFI folder in "EFI OTHER" but with any of those two i'm having some issues:

1. When my Board disk settings are in AHCI the PC just keeps restarting when it hits some point of the installation boot screen and cant get pass that.

2. When my board disk settings are intel fast storage the intallation starts ok but when i open the disk utility the internal hard drive is nowhere to be found.

In the Scenario #2 i tried with a high capacity usb drive and i could install the OS to it, now im triying to boot from it with the clover bootloader in the install usb drive, but at this point its just an experiment since booting mac os from a drive is no an option for me, can you bring some guidance to what am i doing wrong or if i need something else to make this work on my computer.

**Comment by LeeBinder** [comment]
clone the working macOS install from your high capacity usb drive to your internal SSD (e.g. with Carbon Copy Cloner) and boot from it?

**Comment by LeeBinder** [comment]
This repo has found a new home at the current maintainer's GitHub corner:

https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/

If still interested, please download the latest release from over there, **read the _ReadMe_ completely at least once**, and follow all instructions all the way to the end.

In case an issue arises, please post it via the issues section over there.

This issue will now be closed.
