### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by DJohnston79** [tctien342/Asus-Vivobook-S510UA-Hackintosh#34]
What do you use for ethernet?

What does ASUS  smc do and does it replace fake smc?

**Comment by deniro98** [comment]
DWA-131 adapter

**Comment by LeeBinder** [comment]
This repo has found a new home at the current maintainer's GitHub corner:

https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/

If still interested, please download the latest release from over there, **read the _ReadMe_ completely at least once**, and follow all instructions all the way to the end.

In case an issue arises, please post it via the issues section over there.

This issue will now be closed.
