### ISSUE TITLE
Mac 10.15 Backlight Problem

### ISSUE THREAD

**Issue by oneday95** [tctien342/Asus-Vivobook-S510UA-Hackintosh#35]
No fn + F3 + fn + F4 backlight at Mac 10.15 Can you fix it?

**Comment by mrki00** [comment]
I also have this problem and I cant get my sound to work.

**Comment by LeeBinder** [comment]
Have you updated both, VirtualSMC & AsusSMC, to the latest versions?

**Comment by deniro98** [comment]
> I also have this problem and I cant get my sound to work.

You may use VoodoHDA.kext
1. Copy VoodoHDA in /EFI/Clover/kexts/Other
2. Reboot
3. Press space on you macOS drive and select "kext debug", and boot with injected kexts
4. Sound will work with Speakers / Headphones / HDMI. 

FN not working

**Comment by LeeBinder** [comment]
This repo has found a new home at the current maintainer's GitHub corner:

https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/

If still interested, please download the latest release from over there, **read the _ReadMe_ completely at least once**, and follow all instructions all the way to the end.

In case an issue arises, please post it via the issues section over there.

This issue will now be closed.
