### ISSUE TITLE
Lỗi trackpad, bluetooth

### ISSUE THREAD

**Issue by vanhieptech** [tctien342/Asus-Vivobook-S510UA-Hackintosh#36]
Em chào anh,
— Em có lap vivobook s510uq , sau khi cài đặt theo hướng dẫn của anh trackpad dùng được lần đầu tiên...các lần sau em mở lại máy thì không dùng được trackpad nữa ạ. Cái này có phải do xung đột gì không anh?

— Card wifi em thay loại BCM4352 cài kext nhưng chỉ lên được wifi còn bluetooth thì em làm khác nhiều cách trên mạng vẫn không được.

 Mong anh chia sẻ.

Em cảm ơn.

**Comment by deniro98** [comment]
same problem after reboot

**Comment by LeeBinder** [comment]
This repo has found a new home at the current maintainer's GitHub corner:

https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/

If still interested, please download the latest release from over there, **read the _ReadMe_ completely at least once**, and follow all instructions all the way to the end.

In case an issue arises, please post it via the issues section over there.

This issue will now be closed.
