### ISSUE TITLE
Support macOS Catalina 10.15

### ISSUE THREAD

**Issue by helloimfrog** [tctien342/Asus-Vivobook-S510UA-Hackintosh#37]
Như tiêu đề, em mong bác chủ repo sớm hỗ trợ cho macOS Catalina. Em xin donate khi nào bác hoàn thiện cho macOS Catalina

**Comment by deniro98** [comment]
Catalina Works!
[YouTube Touchpad](https://www.youtube.com/watch?v=37CCd5ZgeaQ)
[YouTube Finishing install](https://www.youtube.com/watch?v=tPOpDaa_41U)
Touchpad is awesome works! It's like real macbook! 

Not working:
- FN keys  
- brightness display 
- HDMI
- Battery percentage 

UPD. After 6-7 reboots touchpad is not working)))) i don't know how i can fix it)

**Comment by Jeffernic** [comment]
I hope you can get it as well
God bless you

**Comment by LeeBinder** [comment]
@Jeffernic wrote:
> I hope you can get it as well
> God bless you

???

@deniro98 wrote: 
> UPD. After 6-7 reboots touchpad is not working)))) i don't know how i can fix it)

[Kext Updater](https://bitbucket.org/profdrluigi/kextupdater/downloads/): Tools/ Rebuild kext cache & repair perms[..], reboot

**Comment by boredomdenied** [comment]
So it works except not really considering mojave worked perfectly. Is there anyone who has found a full working solution?

**Comment by LeeBinder** [comment]
What do you mean with "it"?

**Comment by boredomdenied** [comment]
Not working:

FN keys
brightness display
HDMI
Battery percentage

@LeeBinder  Have any of these been resolved? If not you might want to change the README to say that it's not really working with 10.15

I'd really like to upgrade to 10.15 from 10.14 but not having FN keys working is a deal breaker

**Comment by LeeBinder** [comment]
@ boredomdenied : needless to say I can only speak for _**my**_ Vivobook, not for yours... apart from not understanding what deniro98 meant by "brightness display" to begin with.. (maybe you can elaborate since you quoted his list so you must understand what he meant): yes, FN keys (apart from trackpad off via Fn + F9 with legacy VoodooI2C v.2.0.3 installed as indicated in the ReadMe), HDMI (audio not tested because I don't have a HDMI audio device) and battery percentage working perfectly in Catalina 10.15.3 here (10.15.4 beta NOT tested).

Apart from that, I never ever upgrade straight away but always install a fresh virgin next macOS version to a new APFS volume first. If that proves stable after thorough testing, I upgrade my running older OS next (after doing a complete backup). I'd consider one's own testing more relevant than what's written here, or anywhere.

**Comment by boredomdenied** [comment]
So my memory is not the best for what happened when I tried 10.15. I think this was nearly a year ago now. I did attempt to allow the standard upgrade path which must have been a fatal error. It would not boot and I wound up nuking the partition and starting from scratch with Mojave then restoring from TimeMachine.

My rig has populated the m.2 slot for system and uses the 1TB spinner for TimeMachine and media files. I am willing to go through the process to upgrade though would really like to not waste time.

Guess I can try the latest release and go through the process again, but if this happens then how would I restore my prior programs and files using TimeMachine without reverting to 10.14?

**Comment by LeeBinder** [comment]
clone your existing Mojave install via Carbon Copy Cloner. You can always clone that back.

FYI, my 256 GB m.2 SSD hosts EFI (with Clover),  Windows 10 (+ MS EFI) + an APFS container with High Sierra, Mojave and Catalina (+ a Clover backup partition).

1 TB HDD: Data exFat (+ some other partitions not noteworthy mentioning here)

On external USB 3.0 hard disk I have a 1:1 clone of my m.2 SSD so in case something goes wrong I can always boot from it, and even restore.

**Comment by boredomdenied** [comment]
Wow this seems way too complicated for me to focus on right now. Think I'm going to keep it simple and just do a fresh Catalina install and try to have success else revert with timeMachine to Mojave. Maybe I can be free enough to try this out in a few weeks

**Comment by LeeBinder** [comment]
Be smart and wait (possibly only a few days) until the release of the Catalina 10.15.4 update. I (and whatnameisit too, I guess) will test it with latest both kexts and Clover, then share the results here. If all is fine I'll also make a new .dmg release for one-click download :)

**Comment by boredomdenied** [comment]
Yea I'm swamped and chronically sleep deprived so definitely going to put it off for a while. Really appreciate your responses. Thank you for all the good work you're doing
