### ISSUE TITLE
[SOLVED] lag in authentication dialogs (as well as a delayed login screen)/ correct SMBIOS product model

### ISSUE THREAD

**Issue by LeeBinder** [tctien342/Asus-Vivobook-S510UA-Hackintosh#40]
The current release here chooses MacBookPro11,1 as model in SMBIOS as a work-around because with higher model numbers (even the 14,1 of the previous release which is sub optimal, too), lags (e.g. slow password input) are experienced. That is disadvantageous because our Vivobooks have 8th generation CPUs (like in MacBookPro 15,2 & 15,4), but MacBookPro 11,1 has been equipped with much older generation CPUs. **It is mandatory for best performance and best benchmarks that model name matches the CPU as close as possible.**

The solution is very simple: just adding a kext - [NoTouchID](https://github.com/al3xtjames/NoTouchID/releases) + set the best model **MacBookPro15,4**!

From https://github.com/al3xtjames/NoTouchID:

> BiometricKit.framework in 10.13.4+ assumes a Touch ID sensor is present when a compatible board ID is used, which causes lag in authentication dialogs (as well as a delayed login screen). Patching this out resolves such hangs.

@fewtarius who ~~has~~ used to have a Asus Vivobook hackintosh with the same CPU shared with us [here on reddit](https://www.reddit.com/r/hackintosh/comments/d4k4rl/build_asus_2in1_q405ua_i58250u_16gb_ram_uhd_620/f9dzvuo/) the correct model for our Vivobooks:

> MacBookPro14,1 is for 7th gen Core CPUs, so it wouldn't be advisable to use it with an 8th gen. A lot of things could go wrong with that as macOS would load a board plist with parameters that don't match. Wouldn't be surprised to see usb and cpu frequency problems with it, etc. **15,4 and 15,2 are the best matches for an 8th gen Intel laptop**. I did experiment with MacBookAir8,1(and2) as well as MacBook10,1 though and they each had their individual quirks with the 8th gen.

I have been experiencing tangibly better performance ever since applying the NoTouchID kext + setting MBP15,4 in Clover config.

**I M P O R T A N T:**
- For macOS a model change = a hardware change, so Spotlight **_WILL_** be re-indexing -> at first high CPU usage & fan spinning. In Activity Monitor you will see Spotlight processes like mds, mdworker, lsd etc.
- High Sierra requires MPB15,2 in SMBIOS, e.g. via dedicated config-15,2.plist

**Comment by tunglamvghy** [comment]
I think the lag in authentication cause by touchID so just put NoTouchID.kext to Clover/Other to fix it.
