### ISSUE TITLE
[IMPROVED/ OPTION] Touchpad: smoother more reliable 2-finger operations with custom VoodooI2C v.2.0.3

### ISSUE THREAD

**Issue by LeeBinder** [tctien342/Asus-Vivobook-S510UA-Hackintosh#42]
With newer versions of VoodooI2C >= v.2.1, issues have arisen with two finger operations like dragging, highlighting etc. having become unreliable and worse in comparison to VoodooI2C v.2.0.3 and below on many touchpads incl. our Vivobooks' ELAN 1300.

The exact symptoms and more tech details can be read (and even watched in a short video) in the issue "[Support dedicated trackpad buttons to improve horrible dragging/ highlighting](https://github.com/alexandred/VoodooI2C/issues/208)".

The reason is because, starting with VoodooI2C v.2.1, the base engine was swapped with code of the Magic Trackpad 2 ("MT2") which is a 1-button touchpad, but our ELAN 1300 is among those which - even though its surface is made of one piece  - has TWO dedicated buttons underneath, left and right, vs. the one big button device of MT2 touchpads. In other words, any VoodooI2C kexts between v.2.1 and (current as of time of this posting) v.2.3 doesn't match our hardware: they offer more gestures (like pinch zoom) but with the price of frequently loosing/ dropping connection during many (if not most) 2-finger movements!

The original VoodooI2C v.2.0.3 was compiled to run up to High Sierra. Stevezhengshiqi was nice enough to compile it for Mojave and share it with us [here](https://github.com/alexandred/VoodooI2C/issues/70#issuecomment-405458057) ¹, and it even works in Catalina (verified by me on my Vivobook S15 in 10.15.3).

**Until [VoodooInput](https://github.com/acidanthera/VoodooInput) & [VoodooInputEngine](https://github.com/kprinssu/VoodooInputEngine) are fully integrated into VoodooI2C to regain two-button support, this release here will use stevezhengshiqi's fail-safe v.2.0.3 for reasons of reliability and stability.**

If you think you really need all gestures, you can try the latest VoodooI2C from its [release page](https://github.com/alexandred/VoodooI2C/releases), but keep in mind that newer does not always mean better... the main criteria is that kexts/ drivers match the hardware AMAP!!! So if you encounter any of the issues I described [here](https://github.com/alexandred/VoodooI2C/issues/208#issuecomment-566260974), you will have better results with stevezhengshiqi's v.2.0.3 compile already supplied in this release here.

Note that even the v.2.0.3 approach is still not perfect - you might encounter occasional pointer hangs (or even erratic  movements) - but it's as good as it can get for now.
_______________________

¹ disregard his more recent 2.1 and 2.1.1 compiles because they are already based on the MT2 code

**Comment by whatnameisit** [comment]
VoodooI2C now uses VoodooInput (and VoodooInputEngine which has been integrated into VoodooInput) as MT2 emulator: https://github.com/alexandred/VoodooI2C/pull/255
Please try the newest commits.

**Comment by LeeBinder** [comment]
yes thank you - williambj1 had already informed me. Sounds very promising. There doesn't seem to be a public pre-release compile yet. If you have a link or have compiled yourself, feel free to share here :)

[EDIT]: oh, just now I see your link via gitter, how neat. I'm very tired already so I think I'll test tomorrow.

**Comment by LeeBinder** [comment]
This repo has found a new home at the current maintainer's GitHub corner:

https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/

If still interested, please download the latest release from over there, **read the _ReadMe_ completely at least once**, and follow all instructions all the way to the end.

In case an issue arises, please post it via the issues section over there.

This issue will now be closed.
