### ISSUE TITLE
[SOLVED] keyboard backlight in 10.13/14/15

### ISSUE THREAD

**Issue by LeeBinder** [tctien342/Asus-Vivobook-S510UA-Hackintosh#44]
solved with AsusSMC v.1.2.2 from https://github.com/hieplpvip/AsusSMC/releases

**Comment by o0oboao0o** [comment]
Hi, my laptop (ASUS S510) fn + f9 can't disable touchpad. Please help me.

**Comment by LeeBinder** [comment]
This repo has found a new home at the current maintainer's GitHub corner:

https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/

If still interested, please download the latest release from over there, **read the _ReadMe_ completely at least once**, and follow all instructions all the way to the end.

In case an issue arises, please post it via the issues section over there.

This issue will now be closed.
