### ISSUE TITLE
TOUCHPAD » consolidated thread

### ISSUE THREAD

**Issue by LeeBinder** [tctien342/Asus-Vivobook-S510UA-Hackintosh#48]
**[EDIT]**: the [original VoodooI2C](https://github.com/alexandred/VoodooI2C/releases) is mighty fine now. Only this touchpad's usual _occasional_ erratic/ "spastic" pointer movement issues remain.

<details>
  <summary>archived legacy info - click to expand</summary> 

This post's purpose is above all to list this repo's touchpad related issues (regardless of open or closed) in one place to offer a quick and effective way to try out different options if wanted or needed, and possibly offer helpful links and/ or hints of the hackintosh world regarding this Vivobook series' touchpad.

**This repo's touchpad KB (knowledge base):**

- [[IMPROVED/ OPTION] Touchpad: smoother more reliable 2-finger operations with custom VoodooI2C v.2.0.3](https://github.com/tctien342/Asus-Vivobook-S510UA-High-Sierra-10.13-Hackintosh/issues/42)
- [[IMPROVED/ tentatively SOLVED] Touchpad: occasional erratic/ "spastic" pointer movements](https://github.com/tctien342/Asus-Vivobook-S510UA-High-Sierra-10.13-Hackintosh/issues/47)
- [[OPTION] Touchpad: possibly smoother more reliable overall experience with custom polling mode SSDT](https://github.com/tctien342/Asus-Vivobook-S510UA-High-Sierra-10.13-Hackintosh/issues/43)

Also please note that (as also mentioned in this repo's [README.md](https://github.com/tctien342/Asus-Vivobook-S510UA-Hackintosh/blob/master/README.md)) **with VoodooI2C v.2.0.3** (used for now for stability and reliability), **certain minor functions don't work**: Fn+F9 (**Touchpad off/on**) and some touchpad gestures like **pinch zoom**. If for some reason you think you can't live without such, you would need to update to a more recent but buggier version of VoodooI2C from its [release page](https://github.com/alexandred/VoodooI2C/releases).
</details>

**Comment by o0oboao0o** [comment]
Hi, my laptop (ASUS S510) fn + f9 can't disable touchpad. Please help me.

**Comment by LeeBinder** [comment]
@o0oboao0o: I just now included [in this issue's entry posting](https://github.com/tctien342/Asus-Vivobook-S510UA-Hackintosh/issues/48) what I had already written in the ReadMe. Please revisit and read the new paragraph below the bulleted list.

**Comment by yuvrajharod** [comment]
Hello, I have a laptop S15 and I'm unable to use my trackpad for so long and I want it so bad that I just can't tell. I'm very new to Hackintosh and got a bit confused with what all needs to be done from all 3 links. I'm just going to try the I2C's aml file. Can you please create a specific guide on how things should be done from the beginning? It might help a lot. just typing all the processes will help me too.

Thanks

**Comment by LeeBinder** [comment]
HI @yuvrajharod 
You can try as follows:
- download the [v.10.0 release](https://github.com/tctien342/Asus-Vivobook-S510UA-Hackintosh/releases/download/v10.0/v.10.0.Asus-Vivobook-S510UA.Hackintosh.2020-02-24.dmg) - outdated but should work up to macOS Catalina
- apply as per [README.md](https://github.com/tctien342/Asus-Vivobook-S510UA-Hackintosh/blob/master/README.md)
- update ALL kexts incl. [VoodooI2C](https://github.com/alexandred/VoodooI2C/releases) to the latest versions with either [Hackintool](http://headsoft.com.au/download/mac/Hackintool.zip) or [Kext Updater](https://bitbucket.org/profdrluigi/kextupdater/downloads/)
- in terminal, run `sudo kextcache -i /`
- reboot, test, make a backup of /EFI
- Update Clover to [r5122](https://github.com/CloverHackyColor/CloverBootloader/releases/tag/5122) (with this current and latest release here, do **_not_** update Clover beyond 5122 unless you know exactly what you would be doing)
- reboot, test

Good luck 👍

**Comment by yuvrajharod** [comment]
Well as a first help I need something else, As someone suggested and I think this is needed. I think I'll need to delete the AppleINtelLpss.kext from my L/E but I m unable to on my bigsur, can you help me with this if you know......

Thanks

**Comment by LeeBinder** [comment]
I don't have Big Brother installed and don't know anything about a potential need to remove AppleINtelLpss.kext, but you can use Kext Updater -> Tools to make the sys partition writable to delete files from it (via the Start button to the left of 'System Partition Status').

Also I think you can disable kexts with both, Clover and OC.

But above all, you shouldn't use Big Brother as your main macOS, but Catalina or (what I recommend) Mojave.

**Comment by yuvrajharod** [comment]
Well, I tried using the way you told but no luck here. I'm on OC btw. Tried deleting those files but for some reason, they just come back without my consent I can say as soon as I restrt, can you take some time out and connect on-screen to make this thing work if you can and would like to. I'm really sorry if I sound too approachy but I need this thing real bad man.😓

Thanks.

**Comment by LeeBinder** [comment]
sorry @yuvrajharod,I don't have any spare time for a remote session.

Here's what I would do if I were you:

0. add a new APFS volume to your existing APFS container on SSD and label it Mojave (or Catalina)

1. create a non-Big Sur macOS (Mojave or Catalina) installer to USB SSD flash drive or disk with Greg "Munki" Neagle's [installinstallmacos.py script](https://github.com/munki/macadmin-scripts)

2. on that USB disk, also add at least one (but recommend several) FAT32 partition(s)

3. download at least one particular pre-configured setup of one of our two bootloaders, Clover respectively OC. You already have v.10.0 from here, so:
- [if you haven't tried yet, the latest from here with a few updates compared with 10.0](https://github.com/tctien342/Asus-Vivobook-S510UA-Hackintosh/archive/master.zip)
- [the latest OC setup from whatnameisit's X510UA-BQ490 repo](https://github.com/whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.7-Hackintosh/archive/master.zip)
- [whatnameisit's final release containing his Clover setup](https://github.com/whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.7-Hackintosh/archive/1.0.1.zip)
-  [tctien342's Big Sur package](https://github.com/tctien342/Asus-Vivobook-S510UA-Hackintosh/issues/56#issuecomment-671952389) (minus HibernationFixup.kext and SMCDellSensors.kext)

4. Fill each partition on your USB SSD device with one setup

5. Via BIOS UEFI bootmenu, boot the first bootloader setup and try to install macOS <= 10.15.
If that fails, boot the next bootloader entry, etc. until you have macOS <= 10.15 installed

6. Now find the bootloader setup which runs macOS <= 10.15 best

Voila

**Comment by yuvrajharod** [comment]
> sorry @yuvrajharod,I don't have any spare time for a remote session.
> 
> Here's what I would do if I were you:
> 
> 1. add a new APFS volume to your existing APFS container on SSD and label it Mojave (or Catalina)
> 2. create a non-Big Sur macOS (Mojave or Catalina) installer to USB SSD flash drive or disk with Greg "Munki" Neagle's [installinstallmacos.py script](https://github.com/munki/macadmin-scripts)
> 3. on that USB disk, also add at least one (but recommend several) FAT32 partition(s)
> 4. download at least one particular pre-configured setup of one of our two bootloaders, Clover respectively OC. You already have v.10.0 from here, so:
> 
> * [if you haven't tried yet, the latest from here with a few updates compared with 10.0](https://github.com/tctien342/Asus-Vivobook-S510UA-Hackintosh/archive/master.zip)
> * [the latest OC setup from whatnameisit's X510UA-BQ490 repo](https://github.com/whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.7-Hackintosh/archive/master.zip)
> * [whatnameisit's final release containing his Clover setup](https://github.com/whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.7-Hackintosh/archive/1.0.1.zip)
> * [tctien342's Big Sur package](https://github.com/tctien342/Asus-Vivobook-S510UA-Hackintosh/issues/56#issuecomment-671952389) (minus HibernationFixup.kext and SMCDellSensors.kext)
> 
> 1. Fill each partition on your USB SSD device with one setup
> 2. Via BIOS UEFI bootmenu, boot the first bootloader setup and try to install macOS <= 10.15.
>    If that fails, boot the next bootloader entry, etc. until you have macOS <= 10.15 installed
> 3. Now find the bootloader setup which runs macOS <= 10.15 best
> 
> Voila

Okay, I see. that's better too. Thanks for the suggestion mate. Really appreciate your time!

**Comment by LeeBinder** [comment]
This repo has found a new home at the current maintainer's GitHub corner:

https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/

If still interested, please download the latest release from over there, **read the _ReadMe_ completely at least once**, and follow all instructions all the way to the end.

In case an issue arises, please post it via the issues section over there.

This issue will now be closed.
