### ISSUE TITLE
Battery Life is too SHORT !

### ISSUE THREAD

**Issue by wonhee0410** [tctien342/Asus-Vivobook-S510UA-Hackintosh#49]
On Windows my laptop can use for about 5-6hrs but on Hackintosh it's just 2hrs thought the temperature is around 45-50 *C, too high. 
I don't know how to fix, can someone help me ? Thanksss

**Comment by tunglamvghy** [comment]
I think you should check CPUFriend.kext.
If you want battery last longer, choose Macbook Air profile

**Comment by wonhee0410** [comment]
> I think you should check CPUFriend.kext.
> If you want battery last longer, choose Macbook Air profile

Thanks.
But the temperature is always about >= 45*C, is it normal ? I think it's should just about 40*C.
CPUFriend and One-key-CPUFriend is the same, right ? Could you instruct me how to do that, I'm new to hackintosh, thx.
And another thing is when I clicked "Sleep" until after about 15s it completely sleep, it's strange.

**Comment by tunglamvghy** [comment]
My Hackintosh is always 44C.

**Comment by LeeBinder** [comment]
https://github.com/acidanthera/CPUFriend/blob/master/Instructions.md

**Comment by LeeBinder** [comment]
I added different [CPU performance options](https://github.com/tctien342/Asus-Vivobook-S510UA-Hackintosh/tree/master/post%20macOS%20Installations/%5BOptional%5D/change%20CPU%20Performance).

**Comment by LeeBinder** [comment]
Please apply and test [the latest release v.10.0](https://github.com/tctien342/Asus-Vivobook-S510UA-Hackintosh/releases/download/v10.0/v.10.0.Asus-Vivobook-S510UA.Hackintosh.2020-02-24.dmg) and report back after some time. Thank you.

**Comment by LeeBinder** [comment]
My Vivo has a SSD and a HDD. With the HDD mounted I get much worse battery life than if it's unmounted. That also applies after setting disksleep to less than the default 10 mins.

I wrote a little Applescript which mounts or unmounts the HDD:
<details>
  <summary>click to expand</summary> 

```
# specify the name of (one of) the volume(s) on your MacBook's internal HDD:
set myHDD to "Data"

set abortingMsg to "Volume \"" & myHDD & "\" not found - aborting!!"

set Cap to (do shell script "diskutil info disk0 | grep \"Solid State\"")
tell Cap to set {SSD} to {last word}
if SSD = "No" then
	set diskX to "disk0"
	#display dialog "disk0 = HDD!" buttons {"OK"} default button 1 giving up after 10
else
	set Cap to (do shell script "diskutil info disk1 | grep \"Solid State\"")
	tell Cap to set {SSD} to {last word}
	if SSD = "No" and result does not contain "error" then
		set diskX to "disk1"
		#display dialog "disk1 = HDD!" buttons {"OK"} default button 1 giving up after 10
	else
		set diskX to "disk2"
		#display dialog "disk2 = HDD!" buttons {"OK"} default button 1 giving up after 10
	end if
end if

tell application "Finder"
	if not (exists the disk myHDD) then
		try
			#do shell script "diskutil mountDisk '" & diskX & "'"
			do shell script "diskutil mountDisk " & diskX
		on error
			do shell script "diskutil mountDisk " & diskX with administrator privileges
		end try
		
		if not (exists the disk myHDD) then
			display notification abortingMsg
			return 0
		end if
		
		set result to "Volume(s) mounted successfully"
		
		# optional; uncomment if you want to open the mounted volume in Finder
		(*if (exists the disk myHDD) then
			tell application "Finder"
				activate
				make new Finder window
				set target of Finder window 1 to disk myHDD
				set result to "Volume \"" & myHDD & "\" mounted"
			end tell
		else
			set result to abortingMsg
		end if *)
	else
		--display dialog "unmounting now!" buttons {"OK"} default button 1 giving up after 10
		
		try
			do shell script "diskutil eject '" & diskX & "'"
		on error
			display dialog "ATTENTION: The disk can't be ejected because it still appears to be in use.
			
Do you want to try to force-eject it (NOT recommended because data might be lost!)?" buttons {"No", "Yes"} default button 2 with icon stop
			if the button returned of the result is "Yes" then
				do shell script "diskutil unmountDisk force '" & diskX & "'"
			else
				set result to "Script aborted."
			end if
		end try
	end if
end tell

display notification result with title "(Un)Mount HDD:"
```
</details>

![Icon Screenshot](https://user-images.githubusercontent.com/39203497/75932029-b0961880-5e76-11ea-90cf-a0c79e160b82.jpg)

![keyboard shortcut](https://user-images.githubusercontent.com/39203497/75932045-bab81700-5e76-11ea-8af3-b67513a3689e.jpg)

@whatnameisit , any thoughts :)? You feel like testing it? (I know you do :1st_place_medal:)

[(Un)Mount HDD 1.0.3.zip](https://github.com/tctien342/Asus-Vivobook-S510UA-Hackintosh/files/4630485/Un.Mount.HDD.1.0.3.zip)

**Comment by whatnameisit** [comment]
I have two SSDs installed, so I can't test it.
Anyways, HDDs are for storing data. If you want to access something on it, it needs to be mounted. If not, it can be unmounted. Considering you would need to run the app every time you need to access the disk then again to unmount the disk, I recommend you buy a moderate SSD to save battery.

**Comment by LeeBinder** [comment]
now I finally get to reply... sure, two SSDs are the way to go. I don't use the HDD that much so for me this is fine for now, esp. with the keyboard shortcut. In the long run I do plan to replace the HDD with a 2nd SSD.

The "app'ed" script might come in handy for people who don't want to open the laptop case for a disk swap. And I always like to learn new pieces of Applescript and bash, which I like both :)

**Comment by LeeBinder** [comment]
This repo has found a new home at the current maintainer's GitHub corner:

https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/

If still interested, please download the latest release from over there, **read the _ReadMe_ completely at least once**, and follow all instructions all the way to the end.

In case an issue arises, please post it via the issues section over there.

This issue will now be closed.
