### ISSUE TITLE
请问你mac桌面美化软件是什么？

### ISSUE THREAD

**Issue by RockJesus** [tctien342/Asus-Vivobook-S510UA-Hackintosh#5]

**Comment by riletan** [comment]
English Pls

**Comment by tctien342** [comment]
If you mean the widget on my desktop:
http://tracesof.net/uebersicht/

**Comment by LeeBinder** [comment]
This repo has found a new home at the current maintainer's GitHub corner:

https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/

If still interested, please download the latest release from over there, **read the _ReadMe_ completely at least once**, and follow all instructions all the way to the end.

In case an issue arises, please post it via the issues section over there.

This issue will now be closed.
