### ISSUE TITLE
Problem with the config.plist

### ISSUE THREAD

**Issue by johnwtt** [tctien342/Asus-Vivobook-S510UA-Hackintosh#52]
All three of the config.plist not seem to work on my  S510UQ. All seem to have a same problem "This version of Mac OS is not supported on this platform"

**Comment by LeeBinder** [comment]
- version of macOS (like **10.15.3**) missing
- CPU (like **i7-7500U 2.7GHz, 7th Generation**) missing

hey @johnwtt mate, you can do better, can't ye .. ;)

For 7th generation i7-7xxxx CPU I think you could try MacbookPro14,3 in SMBIOS (not sure though).

Also look at https://github.com/nguyentrucxinh/ASUS-VivoBook-X510UQR-Hackintosh
