### ISSUE TITLE
WiFi networks can't be found 

### ISSUE THREAD

**Issue by arstasczak** [tctien342/Asus-Vivobook-S510UA-Hackintosh#53]
Hello, I've got problem with my S510UN. Lately I've updated my hackintosh from High Sierra to Catalina and there is a WiFi issue that I can't figure how to fix it. 

I have BCM94352Z card, which is DW1560 made by Lenovo. Configured freshly installed Catalina through readme and everything works fine, but I am not able to find any WiFi network. There is always empty list. 
![Screenshot 2020-03-31 at 11 15 20](https://user-images.githubusercontent.com/22795206/78009176-eb3d8480-7340-11ea-93da-bbee00f025eb.png)

My WiFi card is found by system.

![Screenshot 2020-03-31 at 11 16 08](https://user-images.githubusercontent.com/22795206/78009248-07412600-7341-11ea-9a26-f3ccd0842b6c.png)

Did someone have similar problem and know how to fix it?

**Comment by LeeBinder** [comment]
don't know right of hand. Am very busy right now - I'll ponder and try reply in a few days hopefully.

**Comment by LeeBinder** [comment]
into terminal, paste
`rebuild kextcache -i`
press ENTER, wait till finished
reboot, recheck

BTW, FYI: the Lenovo variant of the BCM94352Z is called FRU 04X6020 (Vendor ID: 0x0489 | Product ID: 0xE07A). That's the one I have. No probs in 10.13/14/15:

![Screenshot 2020-04-08 at 01 20 05](https://user-images.githubusercontent.com/39203497/78728293-3ce4a100-7937-11ea-810f-194dd66a28cb.jpg)

Comparing your screenie with mine, maybe you might also need to set your country code in Clover Configurator/Boot/Arguments: brcmfx-country=**US** (or where ever you live)

**Comment by arstasczak** [comment]
Changing country code helped, thank you so much! 👍

**Comment by LeeBinder** [comment]
That's great news, thanks for reporting back! I committed a change to this repo with brcmfx-country=US as static value so Wi-Fi networks should always get detected, and the user can edit to his/her country :)
