### ISSUE TITLE
[SOLVED] s510unr won't wake from sleep and minimum display brightness is still too bright

### ISSUE THREAD

**Issue by daninantro** [tctien342/Asus-Vivobook-S510UA-Hackintosh#54]
Hi, I managed to install Mojave on my s510unr. 
In addition to specs mentioned, I have nvidia mx150, 1 x 256GB NVME and 1 x 1TB HDD.

Everything works except when my laptop goes to sleep it doesn't wake up. When I try to wake it up, I just see a cursor and nothing else. Have to force reboot.

Also, the other problem I have is that the lowest display brightness is still too bright and the display colour profile wont do anything. 

Can anyone help to solve these issues? I have been through many google searches but to no avail.

Thanks!

**Comment by daninantro** [comment]
Okay.. I did some research on reddit and found the below fixes for my problems.. 
Vivobooks with dedicated GPU: please add the following bootflag in clover configurator BOOT section:
-wegnoegpu

This will disable dedicated gpu and solve brightness issue.. also it may conserve some battery

Also, the sleep issue was solved after using boot flag : darkwake=10

**Comment by LeeBinder** [comment]
Great & thanks @daninantro - let's keep this open for now. I'll add your findings to the repo.

**Comment by whatnameisit** [comment]
@daninantro 
disable dGPU should already be done with _REG, _WAK and _PTS patches in config.plist and SSDT-S510-KabyLakeR.aml. dGPU patches applied in the ACPI and -wegnoegpu should have the same effect. Are you sure it was -wegnoegpu that fixed the issue?

**Comment by daninantro** [comment]
@whatnameisit 
Yes, -wegnoegpu solved my problem. If I disable the boot flag and restart, I get the same brightness and colour inaccuracy issue.

I was also under the impression that dgpu is disabled by default by using patches. But this hackintosh guide is made for the vivobooks with no dgpu (the laptop config in readme doesn't mention dgpu). So that got me wondering whether the dgpu is actually disabled. Instead of going through the patches I just decided to use the wegnoegpu boot flag as it was easier way to check. 

If anyone else could check this it would be great.

**Comment by whatnameisit** [comment]
@daninantro that's odd. Although this repo doesn't mention anything about disabling dGPU, hieplpvip made the config.plist and the SSDTs which in his repo explicitly states _REG, _PTS, and _WAK are for disabling dGPU in the hotpatch files.
If the patches fail for Vivobooks, it could mean different ACPI patches are needed to do the correct job. You can file an issue with your Clover-extracted ACPI at hieplpvip's Asus-zenbook repo and hopefully he has some time to look at the DSDT. Or you could just leave it alone and let -wegnoegpu handle the dGPU.

**Comment by LeeBinder** [comment]
brief Easter vacation - can add my thoughts in a day or so.

**Comment by daninantro** [comment]
> 
> 
> @daninantro that's odd. Although this repo doesn't mention anything about disabling dGPU, hieplpvip made the config.plist and the SSDTs which in his repo explicitly states _REG, _PTS, and _WAK are for disabling dGPU in the hotpatch files.
> If the patches fail for Vivobooks, it could mean different ACPI patches are needed to do the correct job. You can file an issue with your Clover-extracted ACPI at hieplpvip's Asus-zenbook repo and hopefully he has some time to look at the DSDT. Or you could just leave it alone and let -wegnoegpu handle the dGPU.

Actually I am a newbie, so I dont want to go out of my line to report the issue of the ACPI patches. Maybe I am wrong. So its better that experts like you, @LeeBinder and some others could have a look into the issue before reporting it :) 

At this moment I will stick with easier method of using the bootflag 👍

**Comment by schmosbyy** [comment]
Hi!
I have similar Issue @LeeBinder .
I did however add Dart =0 and darkwake =10 in config.plist But it isnt helping. By display turns on with a black screen and a mouse cursor, and after 2-5 minutes the Machine restarts.
Also If it helps, I have also added "-disablegfxfirmware" in config.plist as without it my Hackintosh won't boot.
Do notify If I need to open up a new issue for this.
Thanks

**Comment by LeeBinder** [comment]
@schmosbyy : I am very pressed on time these days, so let me see what I can contribute:

1. what VivoBook model do you have, with which dedicated graphics?
2. why the dart entry - what is it supposed to do? Have you tried without Dart =0?
3. I am not sure about the space after the = . From what I know it should be darkwake=10. Same would apply to Dart=0, provided it does apply here at all
4. replace VoodooTSCSync.kext with lvs1974's new [CpuTscSync.kext](https://github.com/lvs1974/CpuTscSync/releases), reboot
5. Update to the latest [VoodooI2C 2.4.2](https://github.com/VoodooI2C/VoodooI2C/releases/tag/2.4.2)

If all above has not helped:
6. try  whatnameisit's fabulous [Asus-Vivobook-X510UA-BQ490-Catalina-10.15.4-Hackintosh](https://github.com/whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.4-Hackintosh) repo

Good luck!

**Comment by schmosbyy** [comment]
Wow! Man @LeeBinder you really helped me alot. Thanks alot.
All I had to do was replace VoodoTSCSynch with CpuTscSync(Also updated Voodool2C).
Now The hackintosh is sleeping perfectly even with USB wifi dongle plugged in.
Really do appreciate your help.
By the way,
My asus Vivobook has an "mx150".
Also, a seperate query but does Apple Store work for you? I seem to have the right SMBIOS since ICLOUD and Itunes works perfectly on my machine.

**Comment by LeeBinder** [comment]
Great, glad I could be of help.

Apple Store: yes, it works for me. I'm running Mojave. When I first installed it I re-installed an app I had purchased via Apple Store in High Sierra. I don't think I ever purchased something in Mojave, though.

Make sure Clover Config/ Boot/ brcmfx-country= matches your country, e.g. `brcmfx-country=US` or `brcmfx-country=DE` etc.

**Comment by schmosbyy** [comment]
I already tried the brcmfx-country flag. Appstore seems to work fine on my Mojave (on HDD), though I dont know why it isn't working on Catalina(SSD). 
Ahh well, I guess it's not the end of the world. Thanks for the help!

**Comment by daninantro** [comment]
Hi Guys,
This query is off topic.
I have one query regarding the Intel GPU drivers inbuilt in the Mac OS. Is it possible to disable temporal dithering of Intel GPUs via a kext, because there is no other way to disable the dithering. I checked google very thoroughly for this. 

My eyes hurt real bad when using the MacOS and everything is fine on Windows on the same laptop as I use a program called Ditherig.exe for windows which disables the dithering and makes it very easy on my eyes.

Any updates or insights would be great.

Thanks!

**Comment by LeeBinder** [comment]
@schmosbyy : please be more exact - what exactly isn't working about your Catalina App Store? It's not even launching? Crashing? You can't log in? You can log in and browse through content but not purchase?

I'll log into App Store next time I've booted into Catalina.

I'll try next time I boot Catalina.

**Comment by LeeBinder** [comment]
@daninantro : as you know you're hijacking this thread .. ;) nevertheless, very interesting! I didn't even know until now that this can be an issue.

First a question back to you to please answer: which build of Windows 10 are you running? Does ditherig work with the latest 1909 (or even 2004)?

For those who don't know what this is about, maybe read https://en.wikipedia.org/wiki/Dither#Applications

Basically this appears to be a matter of FRC (Frame rate control), see https://en.wikipedia.org/wiki/Frame_rate_control

I read that the panel itself would need to allow FRC for temporal dithering to be in effect. It also appears that not all panels actually do have this FRC feature.

Long story short, there appears to be **_NO final solution to disable temporal dithering under macOS_**. The dev who appears to know most about this - JTL - wrote in his [OSX dithering - Help wanted](https://ledstrain.org/d/268-osx-dithering-help-wanted/55) topic:

> I wish other people could help but none of this stuff is trivial. I don't mean to sound rude butt talk to me when you have two OS X machines (one as debugging host and the other as "target" where you try and disable dithering on it), a firm grasp of C/C++, X64 Assembly and IDA Pro. Then we can work on this.

Note that the [thread about this issue over at the Apple forum](https://discussions.apple.com/thread/1677617?page=166) has risen to 166 pages over time - no end in sight...

First, for testing for MacBook Pros with dual GPUs (not sure if this also works with h'toshes): [Steve Schow's gfxCardStatus](https://github.com/steveschow/gfxCardStatus/releases).

For now, here's things you can try:
1. via Sys Prefs/ Display, apply a different Color Profile
2. use the Mac version of the free [Iris software](https://iristech.co/iris/)
3. install [SwitchResX](https://www.madrau.com/srx_download/download.html) and set it to use billions instead millions of colors
4. ask headkaze if there is an option somewhere hidden in his hackintool util for disabling dithering with Intel GPUs: [@ tonymac](https://www.insanelymac.com/forum/topic/335018-hackintool-v3xx/?page=36), [@ github](https://github.com/headkaze/Hackintool/issues)
5. [disable font-smoothing system wide](https://osxdaily.com/2018/09/26/fix-blurry-thin-fonts-text-macos-mojave/)
6. use the new Chromium based [Microsoft Edge](https://www.microsoft.com/en-us/edge) for Mac as your browser (the Windows version reportedly has a sharper font rendering algorithm than other browsers, even vs. Google Chrome itself, see [259 ff](https://ledstrain.org/d/152-temporal-dithering-sensitivity-my-solution/259)

Please don't reply here but open a new topic, please. Thanks.

**Comment by whatnameisit** [comment]
@schmosbyy Probably you have USB dongle set as en0 which if not builtin will not allow iCloud account related features. Check that you use RMNE and set that as en0. https://hackintosher.com/guides/quick-fixes-facetime-icloud-imessage-hackintosh-not-working/

**Comment by schmosbyy** [comment]
@LeeBinder  Thanks for being so proactive but as it turns out @whatnameisit suggestion really fixed my issue.
@whatnameisit so basically i did all those steps, but in the end what worked was, I took out the "NullEthernet.kext" from you repository and added it. It seemed to fix the problem with USB Wifi.
You could update this repository in Optional Updates for people who will use USB WIfi.(Just a suggestion.)
Now both my Mojave and Catalina are working at 100%
Thanks alot!

**Comment by whatnameisit** [comment]
@schmosbyy yea, what you did was add RMNE (RehabMan's NullEthernet.kext) and it attached to the fake device RMNE in the main SSDT, so the RMNE device was recognized as a builtin ethernet device, and you cleared the network preferences such as enX mapping, resulting in the builtin ethernet set as en0 and USB dongle as en1.
If this NullEthernet.kext goes in Optional, might as well move RMNE content in the main SSDT to a separate SSDT in Optional...

**Comment by LeeBinder** [comment]
Great - thanks @whatnameisit for taking the time!

Yes, I'll update this repo asap. I'm dancing at quite a few stages at the same time these days so I'm constantly running out of time for hackintosh and simply can't afford night shifts anymore 'cause I have to function during the day, but at some point I'll have some wiggle room again to sit down and polish up v.10.1. Just hang in there, or continue to peek over to [whatnameisit's repo](https://github.com/whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.4-Hackintosh) which is ahead of this one here for the time being.

**Comment by LeeBinder** [comment]
@whatnameisit : regarding FaceTime/ Messages: I have a semi-business ft-meeting with a client tomorrow (she's on ft) so I better finally tackle & fix this tonight. I'll switch to your latest OpenCore release now. Can you just do me a quick favor, simply for confirmation: log into your FaceTime and let me know if you can? Just that would be great. Thank you.

**Comment by whatnameisit** [comment]
@LeeBinder I used FT to call my phone last week and it worked. I left the laptop at home, so I won't be able to check again until 16 hours later. Also, my OpenCore won't be fully compatible with S510U.

**Comment by LeeBinder** [comment]
Thanks @whatnameisit for chiming in - that's good news to begin with.

OC: only things I found that I had to add my `USBPorts.kext` to kexts overwriting yours + `SSDT-ATK-KABY-bkl.aml` & `SSDT-X510UA.aml` to ACPI for kb backlight + add the first to ACPI in OC Configurator, which is rather cosmetic.

I have a `X510UAR` w/o extra Nvidia graphics so it's even closer to yours than tctien342's S510U. From what I read and know nothing else would need to be altered or added, but so correct me if I'm wrong.

Both guides are pretty outdated:
https://hackintosher.com/guides/quick-fixes-facetime-icloud-imessage-hackintosh-not-working/
https://www.tonymacx86.com/threads/an-idiots-guide-to-imessage.196827/

The one that's most current and tailored specifically for OC is:
https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html
because it's most recommended to use a SN with "`Purchase Date not Validated`", which I've done today. The approach to use a SN unknown to Apple supposedly stopped working (and never worked for me before).

Still, I've already spent the past 3 hours trying to get this going (and already several hours some months ago) booted via both, OC and Clover, Mojave & Catalina, and several Apple-IDs, always running the script to clear all settings, reboot, clear NVRAM etc.

Error:

> You cannot sign in to FaceTime on this Mac at this time.
> To use FaceTime with this Mac, contact Apple Support and provide the code below.
>
> Customer Code: ###############
> Apple ID: *************************

I can log into iCloud (Catalina) and AppStore (Catalina, Mojave) no problem.

To be honest, this is the toughest hackintosh project I ever encountered and I start to feel *@#>!&%* .. :(

I am more & more getting the idea that Apple does not like my Lenovo wifi card, even if it's en0 built-in...

Maybe what would help me if you could run [GenSMBIOS](https://github.com/corpnewt/GenSMBIOS) -> 5. List Current SMBIOS, make a screenshot, cut out a vertical bar in the middle to erase a few digits each line, and post it here?

In OC Platforminfo section, I only - in the 1st `Datahub - Generic - PaltformNVRAM` tab - fed the `Generic` section with the SN, MLB and SmUUID generated by GenSMBIOS and verified by the Apple Check Coverage page. The entire section in the SMBIOS tab I left blank, too, which from what I read should be correct?

**Comment by whatnameisit** [comment]
I only use the command lines in the hackintosher.com guide to clean up SMBIOS and Apple ID login information stored on macOS. Then I use Hackintool to generate the numbers for my SMBIOS and it always works for now.
Currently, both structured invalid serial number and "Purchase Date not Validated" number work. It's that Apple blocks some Apple IDs to different levels when they detect invalid logins. Some can only log in on real Macs. Some can log in on PDNV and real Macs. Some can log in on invalid, PDNV, and real Macs. I guess this is until when Apple starts a new policy regarding SMBIOS handling.
I can post GenSMBIOS output when I get home.
And yes, you only have to fill the Generic section. Other fields are for custom configuration for real Macs and legacy hacks.

![스크린샷 2020-12-03 오후 10 57 45](https://user-images.githubusercontent.com/47713349/101027561-7dc2b180-35bb-11eb-984e-5b15febd36c4.png)

**Comment by LeeBinder** [comment]
Thank you @whatnameisit for all the info. My GenSMBIOS output looks almost the same. Even my SN is the same apart from the #s I can't read in the scratchy artwork of yours.. ;)

We ended up doing the transmission in WhatsApp which was fine, but I'll pull a few more strings (much aren't left) on this issue.

> command lines in the hackintosher.com guide to clean up SMBIOS and Apple ID login information

I only see those to remove Apple ID login information:
```
sudo rm -rf ~/Library/Caches/com.apple.iCloudHelper* \
            ~/Library/Caches/com.apple.Messages* \
            ~/Library/Caches/com.apple.imfoundation.IMRemoteURLConnectionAgent* \
            ~/Library/Preferences/com.apple.iChat* \
            ~/Library/Preferences/com.apple.icloud* \
            ~/Library/Preferences/com.apple.imagent* \
            ~/Library/Preferences/com.apple.imessage* \
            ~/Library/Preferences/com.apple.imservice* \
            ~/Library/Preferences/com.apple.ids.service* \
            ~/Library/Preferences/com.apple.madrid.plist* \
            ~/Library/Preferences/com.apple.imessage.bag.plist* \
            ~/Library/Preferences/com.apple.identityserviced* \
            ~/Library/Preferences/com.apple.ids.service* \
            ~/Library/Preferences/com.apple.security* \
            ~/Library/Messages
```
Which command line do you mean to clean up SMBIOS? Or do you simply mean, replace valid w/ invalid or PDNV SN?

I'll generate a new Apple-ID next.

**Comment by LeeBinder** [comment]
PS: I'm sure you don't, but since it's mentioned in the guide, just to make sure: you don't use EmuVariableUefi-64.efi, do you.

**Comment by whatnameisit** [comment]
I have not actually seen what the command lines remove, but they are said to fix previous login information with previous SMBIOS. If you sign in with your Apple ID and switch SMBIOS, a warning pops up that says something like there are problems regarding Apple ID and the pop up may persist even after new signins. Those lines fixes that for me.
And I don't use EmuVariableUEFI. This .efi was made specifically for Clover. For OpenCore you can almost always enable native/emulated NVRAM with just OpenCore. If there are issues, [VariableRuntimeDxe](https://github.com/acidanthera/bugtracker/issues/580) can be used.

**Comment by LeeBinder** [comment]
OK gotcha. I read the VariableRuntimeDxe thread but it's over-the-top for me. The Clover Theme Manager app says "Native NVRAM working". I'm sure you have a more sophisticated way of verifying native/emulated NVRAM.

**Comment by whatnameisit** [comment]
You can write something to NVRAM and see if it's preserved across reboots. See https://dortania.github.io/OpenCore-Post-Install/misc/nvram.html#verifying-if-you-have-working-nvram

**Comment by LeeBinder** [comment]
preserved, which means NVRAM working.

**Comment by LeeBinder** [comment]
This repo has found a new home at the current maintainer's GitHub corner:

https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/

If still interested, please download the latest release from over there, **read the _ReadMe_ completely at least once**, and follow all instructions all the way to the end.

In case an issue arises, please post it via the issues section over there.

This issue will now be closed.
