### ISSUE TITLE
Please include intel wifi kext (as an post installation one) on S510 

### ISSUE THREAD

**Issue by tva2000hn** [tctien342/Asus-Vivobook-S510UA-Hackintosh#57]
There is now support for intel wifi 8265 ac on macos , so i think it would be easier for everyone to install it instead of compiling it from source:

Wifi: https://github.com/OpenIntelWireless/itlwm ( no Airdrop and Hand-off)
HeliPort ( app required to join Wifi networks with the wifi kext above) : https://github.com/OpenIntelWireless/HeliPort
Bluetooth: https://github.com/OpenIntelWireless/IntelBluetoothFirmware

Below are the working complied files: ( tested by me)
Wifi: [itlwm.kext.zip](https://github.com/tctien342/Asus-Vivobook-S510UA-Hackintosh/files/4908816/itlwm.kext.zip)
HeliPort : [HeliPort.zip](https://github.com/tctien342/Asus-Vivobook-S510UA-Hackintosh/files/4908818/HeliPort.zip)
BT: https://github.com/OpenIntelWireless/IntelBluetoothFirmware/releases

Auto-build kexts files (Wifi and HeliPort , untested): https://github.com/1hbb/OpenIntelWireless-Factory

**Comment by LeeBinder** [comment]
great hint, thanks @vapormusic - will do in the upcoming release.

**Comment by schmosbyy** [comment]
@vapormusic Thanks for this info, using this I was able to get the Wifi to work
I however was unable to use Bluetooth(No device Found).
Could you please tell, how/if you did something that may help in me enabling bluetooth.
thanks

**Comment by tva2000hn** [comment]
@schmosbyy there is 2 kexts for BT to work: IntelBluetoothFirmware.kext and IntelBluetoothInjector.kext . Have you put both of those in the clover's kext folder? I don't use BT much but my wireless earphones works.

**Comment by schmosbyy** [comment]
@vapormusic  Yeah I added Both still it isnt working, Can you verify If your hackintool shows the same USB configuration.
Maybe mine is messed up
![Screen Shot 11](https://user-images.githubusercontent.com/22574772/88315803-70a3d500-cd34-11ea-82ea-5e2c115f7ddf.png)
 
**EDIT** : Incase anyone else faces this issue, Try booting into Windows(hoping you have dual boot), this ensures that the bluetooth firmware is loaded into device I guess, and after restart from windows and switching to Catalina, My bluetooth was working!

**Comment by LeeBinder** [comment]
Good. Native Intel BT might also work without booting Windows first if you install the kexts to /L/E instead of loading them via Clover/kexts/Other.

If still not, there is a way to extract the BT firmware from a booted Windows (don't remember how - ReHabMan explained that somewhere), and - if the Intel kext allows that - hopefully inject the extracted firmware during hackOS boot. But I am using a Broadcom replacement in my VivoHackBook, so cannot test but only share what I remember having read somewhere.

**Comment by LeeBinder** [comment]
@schmosbyy are you loading your kexts from EFI/Clover/kexts/Other or from /L/E? Regarding your current necessity to boot Windows first, if you load at least the two BT kexts from /L/E, do you have BT after powering off (not just reboot) and boot into macOS w/o booting Windows first?

**Comment by schmosbyy** [comment]
Yup so these are my findings:

1. The bluetooth to make it work, I had to put the kexts in both L/E as well as Clover(havent notices any instabilities for now atleast)

2. The bluetooth seems to work without needing to boot from windows but it is weird in the sense that, when you fresh turn on your machine(to hackintosh) , It shows as "Bluetooth not available". But after that you should put your device to sleep, wait for 2 minutes and then once the device is awake and logged in the Bluetooth is "ON" and working and connecting fine.

3. One more thing. while I do have toggles for turning Bluetooth on/off(Thanks to Bluetooth injector Kext,maybe?!), if you turn "Off" the bluetooth, it wont turn on again no matter how much tries you do(even if it does, it doesnt connect to any devices).So to fix this, you need to repeat Step 2.

current Status: As long as I dont turn of my Bluetooth from settings, it works and even after I turn the Laptop to Sleep and open again.

**Comment by tva2000hn** [comment]
@schmosbyy i'm not really sure about your bluetooth problems, but here's my EFI folder for you to check out:
https://github.com/vapormusic/smalluploads/blob/master/EFI.7z

**Comment by schmosbyy** [comment]
@vapormusic  There are just a few changes in my kexts , 
1. I have CpuTscSync instead of Voodoo (Since I was having sleep issues.)
2. I dont have itlwm because I honestly feel it is very unstable so I prefer my 10$ tp-link USB wifi.
then again I am quite satisfied with the current bluetooth working(I am okay with making my device sleep for 2 minutes after a cold start if it means uninterrupted bluetooth from there on.)
then again, Appreciate your help!Thanks!

**Comment by LeeBinder** [comment]
@schmosbyy : might be a timing issue. To my surprise, on https://github.com/OpenIntelWireless/IntelBluetoothFirmware it reads:

> **Do _not_** inject the Kext files to `/Library/Extensions` or `/System/Library/Extensions` as it may likely freeze the system.

hmmm..

and below, under **Troubleshooting**:

> In case there is something wrong with the driver, please run the following command in Terminal:
>
>`log show --last boot | grep IntelFirmware`
>
> Save the driver logs, send it to me by opening an issue. **If there are no logs, you should probably check your Bootloader, USB, BIOS, etc.**

You should create a log right after boot **_without_** working BT, and then another log after wake from sleep **_with_** working BT, and send him both.

**Comment by schmosbyy** [comment]
Yeah! thats actually a good Idea.. will do that
(Also having a quad boot system with Mojave along side Catalina, I can afford system freeze ;) )

**Comment by LeeBinder** [comment]
yeah same here:
SSD: Mojave (main OS) and Catalina in one APFS container (thus sharing space); Windows 10 1909 + Aero Glass
HDD: High Sierra (HFS+), Windows 10 2004 (no Aero Glass yet)
(+ a few other OSes incl. Linux, VMs, tool set boot volumes etc.)
.. and all backed up to two external HDDs .. ;)

**Comment by LeeBinder** [comment]
This repo has found a new home at the current maintainer's GitHub corner:

https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/

If still interested, please download the latest release from over there, **read the _ReadMe_ completely at least once**, and follow all instructions all the way to the end.

In case an issue arises, please post it via the issues section over there.

This issue will now be closed.
