### ISSUE TITLE
VivoBook S510UA: Fan runs much slower than on win10 => CPU is thermal throttling => Much Lower performance

### ISSUE THREAD

**Issue by tomakorea** [tctien342/Asus-Vivobook-S510UA-Hackintosh#58]
On the VivoBook S510UA bios 310 (no discrete GPU, and EFI settings as a Macbook Pro 15,4) the fan in High Sierra and Mojave is turning on less than on Windows 10 and also seem to be much slower. It makes the Laptop quieter but there is a huge performance impact.
On Cinebench Windows : around 1250 points,  on Cinebench Mac OS : 825.
It seems like when the cpu is heating up on Mac and reaching 80 degrees the CPU reduce it's frequency drastically instead of blowing air with faster Fan speed.
Is there a way to control Cpu Fan curve manually ?
I checked different situations with Intel Power Gadget in both Mac OS and Windows and it seems it's really related to heat/fan speed. On Win10 Cinebench runs at 2,6Ghz all cores while on Mac it's 1,6Ghz.
Thanks for everything, you did an awesome work.

**Comment by ghost** [comment]
Can also confirm the same issue on my device, hangups often in Safari mostly by thermal throttling

**Comment by tomakorea** [comment]
I noticed that using the Fan MOD ssdt that is on the Clover EFI folder or removing it doesn't change anything on my laptop... the fans still run weak

**Comment by LeeBinder** [comment]
@tomakorea @florinsdistortedvision : https://github.com/tctien342/Asus-Vivobook-S510UA-Hackintosh/tree/master/post%20macOS%20Installations/%5BOptional%5D/change%20CPU%20Performance/MacBookPro15%2C4

You also find the files in the release zip if you downloaded that.

**Comment by tomakorea** [comment]
thank for the answer ! Actually I already tried different profiles corresponding to my Macbook Pro 15,4 settings.
First I tried installing CPUFriend and CPUFriendDataProfider in Library/Extensions and removed it then installed in Clover/Kext/Other. 
- When installed in L/E the CPU Profile is working, I can see it from IntelPowerGadget (CPU Frequencies requested are different from Performance to Power Saving profiles). But the main issue are the fans, the performance profile is there and working well, but the fan speed curve doesn't change at all.
I think the issue comes from the Fan control and not the CPU Profiles with CPUFriend. CPUFriend seems to work nicely.

- Could it be the SSDT-FAN-MOD.aml the problem ? Maybe it doesn t work on some setups ?
My VivoBook S510UA bios 310 has 16gb of RAM (I upgraded it).
- Could it be the issue because the hardware has 16gb of ram ?

**Comment by LeeBinder** [comment]
@tomakorea : a loooong hackintosh time ago I heard from others that more RAM had odd effects it shouldn't have, but I don't even remember exactly what they were, so I can't add anything tangible in that direction.

If you haven't done already, please try [whatnameisit's repo for Vivobooks with no dGPU](https://github.com/whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.6-Hackintosh) (= only Intel UHD 620). He's also far ahead with commits.

First try his Clover EFI folder (rename it to EFI) + your SMBIOS section in clover.plist (easy to copy/paste with PrefEdit) to avoid macOS rebuilds its spotlight index (that would lower bench marks dramatically), then
`sudo chmod -R 755 /L*/E*&&sudo chown -R 0:0 /L*/E*&&sudo kextcache -i /`
to rebuild kext cache, reboot, cinebench.

If still no improvement, create a new >= 100MB FAT or FAT32 partition, call it OpenCore, copy the OpenCore EFI folder to it as /EFI, again feed config.plist with your SN etc. from Clover config.plist, boot it via BIOS, again
`sudo chmod -R 755 /L*/E*&&sudo chown -R 0:0 /L*/E*&&sudo kextcache -i /`
to rebuild kext cache, reboot, cinebench.

Any difference?

**Comment by tomakorea** [comment]
I tried with Clover technique, I had to cleanup my L/E folder because it gave me some kernel panic when launching Intel Power Gadget tool. But after sorting things well, it works as well as before but I still cannot see the difference... I'm starting to wonder if it affects only me and it's an hardware problem ? (maybe bad thermal paste application)
Is someone in the community could try to check if Cinebench is over 20% slower on Win10 than Mac ? I did the test recently with my MacPro Hackintosh but I got the same scores on both OS... so it's not an OS problem.
For the OpenCore method, isn't it safer to create a partition on an USB thumb drive to boot it, instead of mixing things up with clover on the same HDD ?

**Comment by LeeBinder** [comment]
OC on thumb instead internal drive: to me that makes no difference - I have all sorts of EFI volumes on my SSD & HDD. But sure, on a thumb drive is the safer route. It's definitely worth a try.

Cinebench: I don't have time right now, can't promise when

**Comment by LeeBinder** [comment]
> EFI settings as a Macbook Pro 15,4) the fan in High Sierra and Mojave

hmm, High Sierra can't be run with MBP 15,4 model name in SMBIOS but only with MBP15,2 and lower. Can you double-check again which model identifiers(s) you are using?

**Comment by tomakorea** [comment]
I changed to MBP 15,2 to check if it could help. Still get the same results, I will try later replacing my 16gb to 4gb and test it again, but I'm not sure it helps much. How many ram did you install in your Vivobook?

**Comment by LeeBinder** [comment]
This repo has found a new home at the current maintainer's GitHub corner:

https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/

If still interested, please download the latest release from over there, **read the _ReadMe_ completely at least once**, and follow all instructions all the way to the end.

In case an issue arises, please post it via the issues section over there.

This issue will now be closed.
