### ISSUE TITLE
VivoBook S510UQ: Lỗi (Panic on) Wake up

### ISSUE THREAD

**Issue by johnwtt** [tctien342/Asus-Vivobook-S510UA-Hackintosh#59]
Em chào anh, em đang dùng laptop s510uq. Hiện em đang dùng bản EFI mà anh build. Mỗi lần em wake máy thì sẽ bị màn hình đen rồi reboot. Hiện tại dGPU của em vẫn bị detect sau khi dùng flag -wenoegpu và nv-disable=1. Có cách nào giải quyết vấn đề này không ạ.

Em xin đính kèm report

English Translation by Google Translate:

Hi, I'm using laptop s510uq. I am currently using the EFI version that you built. Every time I wake up the machine, the screen will go black and then reboot. Currently my dGPU is still detected after using the flags -wenoegpu and nv-disable = 1. Is there a way to solve this problem?

I attach the report:
<details>
  <summary>click to expand</summary> 

panic(cpu 2 caller 0xffffff7f92650ad5): userspace watchdog timeout: no successful checkins from com.apple.WindowServer in 120 seconds
service: com.apple.logd, total successful checkins since wake (200 seconds ago): 21, last successful checkin: 0 seconds ago
service: com.apple.WindowServer, total successful checkins since wake (200 seconds ago): 8, last successful checkin: 120 seconds ago

Backtrace (CPU 2), Frame : Return Address
0xffffff811706b720 : 0xffffff801151a65d mach_kernel : _handle_debugger_trap + 0x49d
0xffffff811706b770 : 0xffffff8011654a75 mach_kernel : _kdp_i386_trap + 0x155
0xffffff811706b7b0 : 0xffffff80116465fe mach_kernel : _kernel_trap + 0x4ee
0xffffff811706b800 : 0xffffff80114c0a40 mach_kernel : _return_from_trap + 0xe0
0xffffff811706b820 : 0xffffff8011519d27 mach_kernel : _DebuggerTrapWithState + 0x17
0xffffff811706b920 : 0xffffff801151a117 mach_kernel : _panic_trap_to_debugger + 0x227
0xffffff811706b970 : 0xffffff8011cc1b28 mach_kernel : _panic_with_thread_context
0xffffff811706b9e0 : 0xffffff7f92650ad5 com.apple.driver.watchdog : __ZN10IOWatchdog14userspacePanicEP8OSObjectPvP25IOExternalMethodArguments.cold.1 + 0x27
0xffffff811706b9f0 : 0xffffff7f926507fa com.apple.driver.watchdog : __ZN10IOWatchdog35userspaceDisableUserspaceMonitoringEP8OSObjectPvP25IOExternalMethodArguments
0xffffff811706ba10 : 0xffffff8011c539ce mach_kernel : __ZN12IOUserClient14externalMethodEjP25IOExternalMethodArgumentsP24IOExternalMethodDispatchP8OSObjectPv + 0x1de
0xffffff811706ba60 : 0xffffff7f9264fcfe com.apple.driver.watchdog : __ZN20IOWatchdogUserClient14externalMethodEjP25IOExternalMethodArgumentsP24IOExternalMethodDispatchP8OSObjectPv + 0x7c
0xffffff811706bb60 : 0xffffff8011c5cbf3 mach_kernel : _is_io_connect_method + 0x223
0xffffff811706bca0 : 0xffffff80116035e2 mach_kernel : _iokit_server_routine + 0x4e62
0xffffff811706bdb0 : 0xffffff80115203c8 mach_kernel : _ipc_kobject_server + 0x238
0xffffff811706be10 : 0xffffff80114f6d15 mach_kernel : _ipc_kmsg_send + 0x135
0xffffff811706be70 : 0xffffff801150db22 mach_kernel : _mach_msg_overwrite_trap + 0x2d2
0xffffff811706bf00 : 0xffffff801162c065 mach_kernel : _mach_call_munger64 + 0x205
0xffffff811706bfa0 : 0xffffff80114c1226 mach_kernel : _hndl_mach_scall64 + 0x16
      Kernel Extensions in backtrace:
         com.apple.driver.watchdog(1.0)[832CC890-EE61-33E0-8FD4-8D354BCD0921]@0xffffff7f9264f000->0xffffff7f92657fff

BSD process name corresponding to current thread: watchdogd
Boot args: igfxcflbklt=0 keepsyms=1 kext-dev-mode=1 -lilubetaall -alcbeta -wenoegpu 

Mac OS version:
19G73

Kernel version:
Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64
Kernel UUID: 783946EA-6F11-3647-BF90-787AEA14B954
Kernel slide:     0x0000000011200000
Kernel text base: 0xffffff8011400000
__HIB  text base: 0xffffff8011300000
System model name: MacBookAir8,2 (Mac-226CB3C6A851A671)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 1571299305453
last loaded kext at 1362287507202: >!UAudio	323.4 (addr 0xffffff7f96cf6000, size 434176)
last unloaded kext at 1450880745157: ru.joedm.SMCSuperIO	1.1.5 (addr 0xffffff7f95885000, size 49152)
loaded kexts:
com.zxystd.!I!BFirmware	1.0.3
me.kishorprins.VoodooInput	1.0.6
as.acidanthera.voodoo.driver.PS2Keyboard	2.1.5
com.alexandred.VoodooI2CHID	1
ru.joedm.SMCSuperIO	1.1.5
com.alexandred.VoodooI2C	2.4.3
org.coolstar.VoodooGPIO	1.1
com.zxystd.itlwm	1
com.rehabman.driver.ACPIPoller	0.8.1
as.acidanthera.voodoo.driver.PS2!C	2.1.5
com.hieplpvip.AsusSMC	1.2.2
org.rehabman.driver.VoodooTSCSync	1.5.0
as.vit9696.SMCProcessor	1.1.5
as.lvs1974.AirportBrcmFixup	2.0.7
as.vit9696.!AALC	1.5.0
org.vanilla.driver.CPUFriend	1.2.1
xyz.racermaster.NoTouchID	1.0.3
ru.usrsse2.SMCBatteryManager	1
com.alexandred.VoodooI2CServices	1
as.vit9696.WhateverGreen	1.4.0
ru.usrsse2.SMCLightSensor	1
as.vit9696.VirtualSMC	1.1.5
fish.goldfish64.SystemProfilerMemoryFixup	1.0.0
as.vit9696.Lilu	1.4.6
com.rehabman.driver.USBInjectAll	0.7.1
org.tw.CodecCommander	2.7.2
>!ASmartBatteryManager	161.0.0
@AGDCPluginDisplayMetrics	5.2.6
>AudioAUUC	1.70
>!AHV	1
|IOUserEthernet	1.0.1
|IO!BSerialManager	7.0.6f7
>!APlatformEnabler	2.7.0d0
>AGPM	111.4.4
>X86PlatformShim	1.0.0
>pmtelemetry	1
>!AHDA	283.15
@Dont_Steal_Mac_OS_X	7.0.0
>!AUpstreamUserClient	3.6.8
>!A!IKBLGraphics	14.0.7
>!A!IPCHPMC	2.0.1
>!ABacklight	180.3
>!ASMCLMU	212
>eficheck	1
>!A!ISlowAdaptiveClocking	4.0.0
>!A!IKBLGraphicsFramebuffer	14.0.7
>!AMCCSControl	1.14
@private.KextAudit	1.0
@filesystems.ntfs	3.14.3
@filesystems.autofs	3.0
@fileutil	20.036.15
>!ATopCaseHIDEventDriver	3430.1
>!AVirtIO	1.0
@filesystems.hfs.kext	522.100.5
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
@filesystems.apfs	1412.141.1
>!AAHCIPort	341.140.1
>!ARTC	2.0
>!AACPIButtons	6.1
>!AHPET	1.8
>!ASMBIOS	2.1
>!AACPIEC	6.1
>!AAPIC	1.7
$!AImage4	1
@nke.applicationfirewall	303
$TMSafetyNet	8
@!ASystemPolicy	2.0.0
|EndpointSecurity	1
|IOAVB!F	850.1
>DspFuncLib	283.15
@kext.OSvKernDSPLib	529
>!AHDA!C	283.15
|IOHDA!F	283.15
@!AGPUWrangler	5.2.6
>!ABacklightExpert	1.1.0
|IONDRVSupport	576.1
>!ASMBusPCI	1.0.14d1
@plugin.IOgPTPPlugin	840.3
|IOEthernetAVB!C	1.1.0
|IOSkywalk!F	1
>X86PlatformPlugin	1.0.0
>IOPlatformPlugin!F	6.0.0d8
|IOSlowAdaptiveClocking!F	1.0.0
@!AGraphicsDeviceControl	5.2.6
|IOAccelerator!F2	438.7.3
>!ASMBus!C	1.0.18d1
|IOGraphics!F	576.1
@kext.triggers	1.0
|Broadcom!BHost!CUSBTransport	7.0.6f7
|IO!BHost!CUSBTransport	7.0.6f7
|IO!BHost!CTransport	7.0.6f7
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
>!AHS!BDriver	3430.1
>IO!BHIDDriver	7.0.6f7
|IO!B!F	7.0.6f7
|IO!BPacketLogger	7.0.6f7
>!AActuatorDriver	3440.1
>!AMultitouchDriver	3440.1
>!AInputDeviceSupport	3440.8
|IOSerial!F	11
|IOSurface	269.11
@filesystems.hfs.encodings.kext	1
|IOAHCIBlock!S	316.100.5
>usb.!UHostPacketFilter	1.0
|IOUSB!F	900.4.2
|IOAHCI!F	290.0.1
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
>!AEFINVRAM	2.1
>!AEFIRuntime	2.1
|IOHID!F	2.0.0
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
|IOSMBus!F	1.1
|IOAudio!F	300.2
@vecLib.kext	1.2.0
>DiskImages	493.0.0
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!ASSE	1.0
>!AKeyStore	2
>!UTDM	489.120.1
|IOSCSIBlockCommandsDevice	422.120.3
>!ACredentialManager	1.0
>KernelRelayHost	1
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
|IOUSBMass!SDriver	157.140.1
|IOSCSIArchitectureModel!F	422.120.3
|IO!S!F	2.1
|IOUSBHost!F	1.2
>!UHostMergeProperties	1.2
>usb.!UCommon	1.0
>!ABusPower!C	1.0
|CoreAnalytics!F	1
>!AMobileFileIntegrity	1.0.5
@kext.CoreTrust	1
|IOTimeSync!F	840.3
|IONetworking!F	3.4
|IOReport!F	47
>!AACPIPlatform	6.1
>!ASMC	3.1.9
>watchdog	1
|IOPCI!F	2.9
|IOACPI!F	1.4
@kec.pthread	1
@kec.corecrypto	1.0
@kec.Libm	1
</details>

--------------------------

_Edited by admin. Reasons:_
- _English translation added_
- _spoiler added_

**Comment by LeeBinder** [comment]
@johnwtt first see [here](https://github.com/tctien342/Asus-Vivobook-S510UA-Hackintosh/issues/56#issuecomment-668803745) and follow the instructions.

**Comment by johnwtt** [comment]
I did what thay said but it still happen

**Comment by LeeBinder** [comment]
Try the following:
1. with Clover Configurator, in the Boot section
**_remove_** (!!)
`nv-disable = 1`
and **_add_**
`darkwake=10`
**save**.
2. in Terminal:
`sudo chmod -R 755 /L*/E*&&sudo chown -R 0:0 /L*/E*&&sudo kextcache -i /`
press **enter** to rebuild kext cache
**reboot**

Any change?

**Comment by johnwtt** [comment]
it works. Thank you

**Comment by LeeBinder** [comment]
Great to hear that, John. Enjoy your VivoHack 👍
