### ISSUE TITLE
Bị lỗi màn hình khi sleep

### ISSUE THREAD

**Issue by devcongvan** [tctien342/Asus-Vivobook-S510UA-Hackintosh#6]
Cảm ơn bạn đã build bản hackintosh dành cho vivobook tốt đến vậy, mình đã cái thành công trên vivobook A510U của mình.
Mọi thứ rất hoàn hảo, chỉ trừ màn hình khi sleep màn hình mình bị lỗi như thế này: 
[image](https://drive.google.com/open?id=1-r75DXyyk_RJQZbJyxbv7fu6ZtPonH-8)
Bạn có thể xem giúp mình được không. Cảm ơn bạn nha

**Comment by tctien342** [comment]
Bác tự tìm edid của màn hình mình r pass vô phần graphic -> inject EDID ấy, nếu xài chung dòng lap vs em thì thử cái file BQ414T trong thư mục config xem

**Comment by devcongvan** [comment]
Cảm ơn bác nhiều quá. Em vừa fix được rùi ^^.
Bác sp vậy em cảm kích quá ^^. Mong là bác cập nhật OS mới cho dòng này thường xuyên :))
Thật với bác là em mới vọc hackintosh nên mới chỉ biết tìm các clover với patch phù hợp để cài thui bác ạ :))

**Comment by tctien342** [comment]
Mới vọc còn nhiều cái hay đang chờ lắm =))), bác tìm được cái gì hay hơn post vô để e update lên nhé :)), bộ này lên đc mac beta mới nhất luôn nhé bác 10.14 ấy :))))

**Comment by awebhay** [comment]
Bác cho em xin ketch TrackPad với. Của em bị lỗi cứ đơ đơ hoặc chạy hoài không dừng lại được.

**Comment by LeeBinder** [comment]
This repo has found a new home at the current maintainer's GitHub corner:

https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/

If still interested, please download the latest release from over there, **read the _ReadMe_ completely at least once**, and follow all instructions all the way to the end.

In case an issue arises, please post it via the issues section over there.

This issue will now be closed.
