### ISSUE TITLE
Mic issue using opencore

### ISSUE THREAD

**Issue by DJohnston79** [tctien342/Asus-Vivobook-S510UA-Hackintosh#60]
Hey sir, my audio codec is cx 8150. 

On clover, evertyhing worked. 

On opencore, no mic. I have tried the opencore troubleshooting for audio and all is according to that guide. 

I have tried using hpet.aml but issue is still there. 

I have tried both layouts to no avail, 21, 22. 

Not sure what else I can do?

**Comment by LeeBinder** [comment]
Which VivoBook are you running that you have CX8150? Also please write your version(s) of macOS.

Have you tried [whatnameisit's OpenCore EFI](https://github.com/whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.6-Hackintosh/tree/master/OpenCore%20EFI/EFI)? Mind that his VivoBook also has CX8050 so his OC EFI might not work for you, either.

Have you tried with or without CodecCommander.kext in /L/E?

Also please note that I do not use OC so cannot really with OC in general.

**Comment by ghost** [comment]
Try to use the bootarg alcid=(the layout you selected and worked on you before). This is what fixed it for me on OpenCore and latest version of kexts.

**Comment by LeeBinder** [comment]
@florinsdistortedvision  in OC Configurator I found bootargs in the NVRAM section. Is that the correct place to add `alcid=##`, e.g. `alcid=13` for CX8050?

**Comment by ghost** [comment]
Yes, it is, obv replace the ## with the layout that worked on you before. For 8150 you should try either alcid=21 or alcid=22. Also injecting layout-id in Device Proprietes may work too.

**Comment by LeeBinder** [comment]
thanks @florinsdistortedvision - for my CX8050 adding `alcid=13` in OC NVRAM/ bootargs (and in Clover in the Boot section) was the do-jobbie to have working mic w/o CodecCommander. One kext less = better :)

**Comment by ghost** [comment]
No problem, i have 8050 too and I use alcid=13 as well, works like a charm

**Comment by LeeBinder** [comment]
If you have a monitor with HDMI audio in (I don't), does it still work with CodecCommander removed? I think I remember that was the problem.

**Comment by ghost** [comment]
Yes it does, latest AppleALC and that bootarg fixes everyproblem. I tested it with my TV

**Comment by LeeBinder** [comment]
This repo has found a new home at the current maintainer's GitHub corner:

https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/

If still interested, please download the latest release from over there, **read the _ReadMe_ completely at least once**, and follow all instructions all the way to the end.

In case an issue arises, please post it via the issues section over there.

This issue will now be closed.
