### ISSUE TITLE
Battery Threshold

### ISSUE THREAD

**Issue by tunglamvghy** [tctien342/Asus-Vivobook-S510UA-Hackintosh#61]
Are there any ways to limit the maximum bqttery level to 80% like My Asus app in Windows?
I found it on a [linux forum](https://wiki.archlinux.org/index.php/ASUS_Zenbook_UX430/UX530#Battery_charge_threshold)

> Most newer Zenbooks supports specifying a charge stop threshold (see ASUS Battery Health Charging for more information).
> 
> The battery charge stop threshold can be set by modifying the EC registers, which can be done with acpi_call. Finding the correct EC register to modify, is the tricky part.
> 
> You can check the current threshold and battery percent, with the following commands:
> 
> ```
> $ read () { echo "${1}" > /proc/acpi/call; printf "%d\n" $(sed 's/\x0.*//g' /proc/acpi/call); }
> $ read "\_SB.PCI0.LPCB.EC0.RRAM 0x3af"
> 100 # Percent at which the battery will stop charging (default is 100)
> $ read "\_SB.PCI0.LPCB.EC0.RRAM 0x3b0"
> 80 # current battery percent, should match: cat /sys/class/power_supply/BAT0/capacity
> ```
> 
> Warning: Do not proceed if the commands do not return the expected values!
> 
> The threshold can be changed with the following command (the threshold is reset when the computer is power cycled):
> 
> `$ echo "\_SB.PCI0.LPCB.EC0.WRAM 0x3af <battery percent in hex, ex: 0x50 for 80%>" > /proc/acpi/call`
> 
> The hex value can be found with `printf "0x%x\n" 80`
> 
> To change the threshold at boot it is possible to use systemd-tmpfiles.
> 
> `/etc/tmpfiles.d/battery.conf`
> `w /proc/acpi/call - - - - \\_SB.PCI0.LPCB.EC0.WRAM 0x3af 0x50 # 80%`

**Comment by tunglamvghy** [comment]
https://patchwork.kernel.org/patch/11125631/

**Comment by LeeBinder** [comment]
No exact idea. I saw this discussed somewhere already - in another github repo, or @ tonymac, or @ insanelymac (don't remember).

Basically all that's theoretically needed is a way via terminal to stop charging the battery. The battery charge itself can be queried via the SOLB (Sleep on low battwery) script at either [insanelymac](https://www.insanelymac.com/forum/topic/336414-release-sleeponlowbattery-%E2%80%9Csolb%E2%80%9D/) or [tonymac](https://www.tonymacx86.com/threads/release-sleeponlowbattery-solb.264785/). The script could be adapted to stop charging the battery at 80%.

BTW, why 80%? Why not 99% or whatever #%? What's so distinct about 80%?

**Comment by hieplpvip** [comment]
This could (and should) be done with WMI. No need to meddle with EC0 as we don't know the exact register for each model.

I'll add support for this in AsusSMC.

**Comment by LeeBinder** [comment]
Awesome! Thank you @hieplpvip

**Comment by tunglamvghy** [comment]
> This could (and should) be done with WMI. No need to meddle with EC0 as we don't know the exact register for each model.
> 
> I'll add support for this in AsusSMC.

Thank you. I'll wait for this feature in the next version of AsusSMC.

**Comment by LeeBinder** [comment]
Just for completeness: https://github.com/hieplpvip/AsusSMC/releases
