### ISSUE TITLE
Bug - Ultrawide videos visual glitches and flickering

### ISSUE THREAD

**Issue by ghost** [tctien342/Asus-Vivobook-S510UA-Hackintosh#63]
Describe the bug
While playing ultrawide Youtube videos, in fullscreen, various visual glitches and flickering appear.

To Reproduce

Go to https://youtu.be/PUrB5MvEPqQ
Select 1080p and fullscreen
Wait for the menu controls to disappear and wait a bit
See error
Expected behavior
Video should play without problems.

Additional context
A semi-fix that I found is rolling back the WhateverGreen kext from the latest one, to the 1.3.7 version which is odd, whenever updating it, the glitch happens again.

S510UA
i7 8550u, 8GB ram, UHD 620

**Comment by johnwtt** [comment]
WhateverGreen bug?
Are you using OC build ?

**Comment by ghost** [comment]
It seems to be indeed a WhateverGreen issue for some reason. As I said running the latest version make ultrawide videos (such as MKBHD videos or LinusTechTips videos) glitch and flicker every 4-5 seconds after menu controls are gone. Having menu controls or right clicking the videos fixes the glitches.

I am using latest OC however the glitch is present in Clover too (i had the latest clover before switching to OpenCore).

**Comment by LeeBinder** [comment]
Hi @florinsdistortedvision . This is clearly a WEG issue. I stopped updating WEG. I don't have any issues with that YT video from your link with WEG 1.3.8. Would you please copy your question over to

main topic: https://www.insanelymac.com/forum/topic/325987-whatevergreen-support-topic/?page=55

and/or

rather meant as a guide: https://www.tonymacx86.com/threads/guide-intel-framebuffer-patching-using-whatevergreen.256490/page-111

and close this issue (and also https://github.com/tctien342/Asus-Vivobook-S510UA-Hackintosh/issues/62)?

Thanks.

**Comment by ghost** [comment]
Sure, no worries, thank you for clarifying the issue is WEG.
