### ISSUE TITLE
Is video working for you in FaceTime running Catalina?

### ISSUE THREAD

**Issue by LeeBinder** [tctien342/Asus-Vivobook-S510UA-Hackintosh#64]
Are you running Catalina on your VivoBook? If so, does video in FaceTime work, meaning: do you see yourself looking into the camera?

I only see black in the window where I should see myself even though the green LED next to the cam is on. The cam works fine in Foto Booth and Skype, and also in FaceTime Mojave. And is also works when I boot Catalina in safe mode via the -x switch in Clover. So something is blocking.

This happens regardless if:
- booting via Clover or OC
- kexts loaded via EFI or installed to /L/E
- most curennt or older versions of kexts

**Comment by abhishekthomasv** [comment]
Sir i too had the same webcam issue in face time .

**Comment by LeeBinder** [comment]
This repo has found a new home at the current maintainer's GitHub corner:

https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/

If still interested, please download the latest release from over there, **read the _ReadMe_ completely at least once**, and follow all instructions all the way to the end.

In case an issue arises, please post it via the issues section over there.

This issue will now be closed.
