### ISSUE TITLE
Little OT for Asus X420UA and Audio Card Kext

### ISSUE THREAD

**Issue by WizardingStudios** [tctien342/Asus-Vivobook-S510UA-Hackintosh#65]
Hello, I have a Vivobook x420ua and with your kext I have now Catalina working. At this moment the only things not working are the webcam and my really only needs: the audio!
Searched everywhere but found nothing about my specs... Hope you should help me in some way...
Many thanks for this absolutely great work! ^^

**Comment by LeeBinder** [comment]
Sorry I don't know the specs of your Vivobook x420ua.
