### ISSUE TITLE
Hey, man can you make blog post about it, describing the exact steps please.

### ISSUE THREAD

**Issue by walidmahade** [tctien342/Asus-Vivobook-S510UA-Hackintosh#7]
I have the asus x510u vivobook.
Hardware exactly same as your reference one.

**Comment by LeeBinder** [comment]
This repo has found a new home at the current maintainer's GitHub corner:

https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/

If still interested, please download the latest release from over there, **read the _ReadMe_ completely at least once**, and follow all instructions all the way to the end.

In case an issue arises, please post it via the issues section over there.

This issue will now be closed.
