### ISSUE TITLE
Can you elaborate the touchpad part?

### ISSUE THREAD

**Issue by saiftheboss7** [tctien342/Asus-Vivobook-S510UA-Hackintosh#8]
https://github.com/tctien342/Asus-Vivobook-S510UA-High-Sierra-10.13-Hackintosh/blob/master/README.md 

Thanks for the great guide! Very helpful. I have got just a question about getting basic touchpad support. I also have the same Elan1300 touchpad. But I could not understand properly where I have to replace the text you provided.

I have already installed latest I2C and I2CHID from https://github.com/hieplpvip/VoodooI2C.

Any thoughts would be very helpful. Thanks in advance.

**Comment by LeeBinder** [comment]
This repo has found a new home at the current maintainer's GitHub corner:

https://github.com/LeeBinder/Asus-Vivobook-S510UA-Hackintosh/

If still interested, please download the latest release from over there, **read the _ReadMe_ completely at least once**, and follow all instructions all the way to the end.

In case an issue arises, please post it via the issues section over there.

This issue will now be closed.
