### ISSUE TITLE
Không thể Sleep cho S510UQ

### ISSUE THREAD

**Issue by nghminh163** [tctien342/Asus-Vivobook-S510UA-Hackintosh#9]
Em dùng S510UQ ạ, khác mỗi có card rời nhưng em dùng card liền ạ. Em không sleep được ạ, bấm sleep nó đen màn rồi lại sáng ạ. Bác biết giúp em với ạ, Em cảm ơn bác nhiều ạ

**Comment by tctien342** [comment]
do chưa disable card rời ấy, mình mới quăng file ssdt tắt card lên, bạn thử lại xem :))
